In [1]:
import numpy as np
from fastembed import TextEmbedding

In [2]:
documents = [
    {'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
     'section': 'General course-related questions',
     'question': 'Course - Can I still join the course after the start date?',
     'course': 'data-engineering-zoomcamp'},

    {'text': 'Yes, we will keep all the materials after the course finishes, so you can follow the course at your own pace after it finishes.\nYou can also continue looking at the homeworks and continue preparing for the next cohort. I guess you can also start working on your final capstone project.',
     'section': 'General course-related questions',
     'question': 'Course - Can I follow the course after it finishes?',
     'course': 'data-engineering-zoomcamp'},

    {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first “Office Hours'' live.\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
     'section': 'General course-related questions',
     'question': 'Course - When will the course start?',
     'course': 'data-engineering-zoomcamp'},

    {'text': 'You can start by installing and setting up all the dependencies and requirements:\nGoogle cloud account\nGoogle Cloud SDK\nPython 3 (installed with Anaconda)\nTerraform\nGit\nLook over the prerequisites and syllabus to see if you are comfortable with these subjects.',
     'section': 'General course-related questions',
     'question': 'Course - What can I do before the course starts?',
     'course': 'data-engineering-zoomcamp'},

    {'text': 'Star the repo! Share it with friends if you find it useful ❣️\nCreate a PR if you see you can improve the text or the structure of the repository.',
     'section': 'General course-related questions',
     'question': 'How can we contribute to the course?',
     'course': 'data-engineering-zoomcamp'}
]

In [3]:
len(documents)

5

In [4]:
embedding_model = TextEmbedding("jinaai/jina-embeddings-v2-small-en")

In [5]:
query = "I just discovered the course. Can I join now?"

In [6]:
query_vector = list(embedding_model.embed([query]))[0]

In [7]:
len(query_vector)

512

In [8]:
texts = [doc['text'] for doc in documents]

In [9]:
len(texts)

5

In [10]:
texts[0]

"Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute."

In [11]:
doc_vectors = list(embedding_model.embed(texts))

In [12]:
len(doc_vectors)

5

In [13]:
len(doc_vectors[0])

512

In [14]:
V = np.array(doc_vectors)

In [15]:
np.array(doc_vectors)

array([[-0.0249525 , -0.0396454 , -0.00437672, ...,  0.06779866,
         0.0377203 , -0.00470724],
       [-0.0594709 , -0.08523984,  0.01292091, ...,  0.09599709,
         0.05420843, -0.00029461],
       [-0.06817788, -0.04089313,  0.05077615, ...,  0.06633986,
         0.02860711, -0.01122149],
       [-0.04640506, -0.02555229,  0.02241224, ...,  0.03410312,
         0.06813592, -0.0064033 ],
       [-0.05394912, -0.04693814,  0.00794725, ...,  0.05402997,
         0.03033385, -0.01254518]], shape=(5, 512))

In [16]:
V.shape

(5, 512)

In [17]:
scores = V.dot(query_vector)

In [18]:
print() scores

SyntaxError: invalid syntax (2803578422.py, line 1)

In [19]:
print(scores)

[0.76296847 0.81823782 0.8113294  0.7133079  0.73044992]

In [20]:
best_index = scores.argmax()
best_index

np.int64(1)

In [21]:
for i, score in enumerate(scores):
    print(i, score)

0 0.7629684696540238
1 0.8182378150042889
2 0.8113294032109533
3 0.7133079015686243
4 0.73044992343336

In [22]:
for i, doc in enumerate(documents):
    print(i, doc['question'])

0 Course - Can I still join the course after the start date?
1 Course - Can I follow the course after it finishes?
2 Course - When will the course start?
3 Course - What can I do before the course starts?
4 How can we contribute to the course?

In [23]:
V_norm = V / np.linalg.norm(V, axis=1, keepdims=True)

In [24]:
q_norm = query_vector / np.linalg.norm(query_vector)

In [25]:
cosine_scores = V_norm.dot(q_norm)

In [26]:
for i, score in enumerate(cosine_scores):
    print(i, score)

0 0.7629684696540238
1 0.8182378150042889
2 0.8113294032109533
3 0.7133079015686243
4 0.73044992343336

In [27]:
best_index = cosine_scores.argmax()
best_index

np.int64(1)

In [30]:
full_texts = [doc['question'] + ' ' + doc['text'] for doc in documents]

In [31]:
full_texts[0]

"Course - Can I still join the course after the start date? Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute."

In [32]:
full_doc_vectors = list(embedding_model.embed(full_texts))

In [33]:
V_full = np.array(full_doc_vectors)

In [34]:
V_full.shape

(5, 512)

In [35]:
full_scores = V_full.dot(query_vector)

In [36]:
for i, score in enumerate(full_scores):
    print(i, score)

0 0.8514543236908068
1 0.843659415911307
2 0.8429645231665941
3 0.7755157969663907
4 0.8086007795043937

In [37]:
best_full_index = full_scores.argmax()
best_full_index

np.int64(0)

In [38]:
V_full_norm = V_full / np.linalg.norm(V_full, axis=1, keepdims=True)
q_norm = query_vector / np.linalg.norm(query_vector)

full_cosine_scores = V_full_norm.dot(q_norm)

for i, score in enumerate(full_cosine_scores):
    print(i, score)

best_full_index = full_cosine_scores.argmax()
best_full_index

0 0.8514543236908068
1 0.843659415911307
2 0.8429645231665941
3 0.7755157969663907
4 0.8086007795043937

np.int64(0)

In [39]:
embedding_model_small = TextEmbedding("BAAI/bge-small-en")

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
C:\Users\felix\vector-search\.venv\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\felix\AppData\Local\Temp\fastembed_cache\models--Qdrant--bge-small-en. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
2026-04-01 12:59:18.212 | ERROR    | fastembed.common.model_management:download_model:446 - Could not download model from HuggingFace: [WinError 1314] Le client ne dispose pas d’un privilège nécessaire: '..\\..\\blobs\\d24f8d0cfab6e6a99fca53c1143c7d780aeb210c' -> 'C:\\Users\\felix\\AppData\\Local\\Temp\\fastembed_cache\\models--Qdrant--bge-small-en\\snapshots\\8791246cc2a79c7949a4dc0d4a018cbd7d024879\\config.json' Falling back to other sources.

  0%|                                                                                     | 0.00/77.7M [00:00<?, ?iB/s]
  2%|█▏                                                                          | 1.23M/77.7M [00:00<00:06, 12.2MiB/s]
  4%|██▊                                                                         | 2.93M/77.7M [00:00<00:05, 14.9MiB/s]
  7%|█████▎                                                                      | 5.40M/77.7M [00:00<00:03, 19.3MiB/s]
 10%|███████▋                                                                    | 7.83M/77.7M [00:00<00:03, 21.2MiB/s]
 13%|██████████                                                                  | 10.3M/77.7M [00:00<00:02, 22.5MiB/s]
 16%|████████████▎                                                               | 12.6M/77.7M [00:00<00:02, 22.2MiB/s]
 19%|██████████████▊                                                             | 15.1M/77.7M [00:00<00:02, 23.2MiB/s]
 23%|█████████████████▏                                                          | 17.6M/77.7M [00:00<00:02, 23.6MiB/s]
 26%|███████████████████▌                                                        | 19.9M/77.7M [00:00<00:02, 23.4MiB/s]
 29%|█████████████████████▊                                                      | 22.3M/77.7M [00:01<00:02, 23.4MiB/s]
 32%|████████████████████████                                                    | 24.6M/77.7M [00:01<00:02, 23.2MiB/s]
 35%|██████████████████████████▍                                                 | 27.0M/77.7M [00:01<00:02, 23.2MiB/s]
 38%|████████████████████████████▋                                               | 29.3M/77.7M [00:01<00:02, 22.9MiB/s]
 41%|███████████████████████████████▍                                            | 32.1M/77.7M [00:01<00:01, 24.1MiB/s]
 46%|██████████████████████████████████▋                                         | 35.5M/77.7M [00:01<00:01, 27.0MiB/s]
 49%|█████████████████████████████████████▎                                      | 38.2M/77.7M [00:01<00:01, 26.1MiB/s]
 53%|███████████████████████████████████████▉                                    | 40.8M/77.7M [00:01<00:01, 25.8MiB/s]
 56%|██████████████████████████████████████████▋                                 | 43.6M/77.7M [00:01<00:01, 26.3MiB/s]
 60%|█████████████████████████████████████████████▏                              | 46.2M/77.7M [00:01<00:01, 26.3MiB/s]
 63%|████████████████████████████████████████████████                            | 49.1M/77.7M [00:02<00:01, 26.6MiB/s]
 67%|██████████████████████████████████████████████████▌                         | 51.7M/77.7M [00:02<00:00, 26.6MiB/s]
 70%|█████████████████████████████████████████████████████▏                      | 54.4M/77.7M [00:02<00:00, 26.5MiB/s]
 73%|███████████████████████████████████████████████████████▊                    | 57.0M/77.7M [00:02<00:00, 25.9MiB/s]
 77%|██████████████████████████████████████████████████████████▉                 | 60.2M/77.7M [00:02<00:00, 27.5MiB/s]
 81%|█████████████████████████████████████████████████████████████▊              | 63.1M/77.7M [00:02<00:00, 27.8MiB/s]
 85%|████████████████████████████████████████████████████████████████▉           | 66.4M/77.7M [00:02<00:00, 27.8MiB/s]
 90%|████████████████████████████████████████████████████████████████████▎       | 69.8M/77.7M [00:02<00:00, 29.5MiB/s]
 94%|███████████████████████████████████████████████████████████████████████▌    | 73.1M/77.7M [00:02<00:00, 30.0MiB/s]
100%|████████████████████████████████████████████████████████████████████████████| 77.7M/77.7M [00:03<00:00, 25.8MiB/s]

In [40]:
query_vector_small = list(embedding_model_small.embed([query]))[0]

In [41]:
len(query_vector_small)

384

In [43]:
import requests

In [44]:
docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'

In [45]:
docs_response = requests.get(docs_url)

In [46]:
documents_raw = docs_response.json()

In [47]:
type(documents_raw), len(documents_raw)

(list, 3)

In [48]:
documents_raw[0]

{'course': 'data-engineering-zoomcamp',
 'documents': [{'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
   'section': 'General course-related questions',
   'question': 'Course - When will the course start?'},
  {'text': 'GitHub - DataTalksClub data-engineering-zoomcamp#prerequisites',
   'section': 'General course-related questions',
   'question': 'Course - What are the prerequisites for this course?'},
  {'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
   'section': 'General course-related questions',
   'question': 'Course - Can I still join the course after the start date?'},
  {'text': "You don't need it. You're accepted. You can also just start learning and submitting homework without registering. It is not checked against any registered list. Registration is just to gauge interest before the start date.",
   'section': 'General course-related questions',
   'question': 'Course - I have registered for the Data Engineering Bootcamp. When can I expect to receive the confirmation email?'},
  {'text': 'You can start by installing and setting up all the dependencies and requirements:\nGoogle cloud account\nGoogle Cloud SDK\nPython 3 (installed with Anaconda)\nTerraform\nGit\nLook over the prerequisites and syllabus to see if you are comfortable with these subjects.',
   'section': 'General course-related questions',
   'question': 'Course - What can I do before the course starts?'},
  {'text': "There are 3 Zoom Camps in a year, as of 2024. However, they are for separate courses:\nData-Engineering (Jan - Apr)\nMLOps (May - Aug)\nMachine Learning (Sep - Jan)\nThere's only one Data-Engineering Zoomcamp “live” cohort per year, for the certification. Same as for the other Zoomcamps.\nThey follow pretty much the same schedule for each cohort per zoomcamp. For Data-Engineering it is (generally) from Jan-Apr of the year. If you’re not interested in the Certificate, you can take any zoom camps at any time, at your own pace, out of sync with any “live” cohort.",
   'section': 'General course-related questions',
   'question': 'Course - how many Zoomcamps in a year?'},
  {'text': 'Yes. For the 2024 edition we are using Mage AI instead of Prefect and re-recorded the terraform videos, For 2023, we used Prefect instead of Airflow..',
   'section': 'General course-related questions',
   'question': 'Course - Is the current cohort going to be different from the previous cohort?'},
  {'text': 'Yes, we will keep all the materials after the course finishes, so you can follow the course at your own pace after it finishes.\nYou can also continue looking at the homeworks and continue preparing for the next cohort. I guess you can also start working on your final capstone project.',
   'section': 'General course-related questions',
   'question': 'Course - Can I follow the course after it finishes?'},
  {'text': 'Yes, the slack channel remains open and you can ask questions there. But always sDocker containers exit code w search the channel first and second, check the FAQ (this document), most likely all your questions are already answered here.\nYou can also tag the bot @ZoomcampQABot to help you conduct the search, but don’t rely on its answers 100%, it is pretty good though.',
   'section': 'General course-related questions',
   'question': 'Course - Can I get support if I take the course in the self-paced mode?'},
  {'text': 'All the main videos are stored in the Main “DATA ENGINEERING” playlist (no year specified). The Github repository has also been updated to show each video with a thumbnail, that would bring you directly to the same playlist below.\nBelow is the MAIN PLAYLIST’. And then you refer to the year specific playlist for additional videos for that year like for office hours videos etc. Also find this playlist pinned to the slack channel.\nh\nttps://youtube.com/playlist?list=PL3MmuxUbc_hJed7dXYoJw8DoCuVHhGEQb&si=NspQhtZhZQs1B9F-',
   'section': 'General course-related questions',
   'question': 'Course - Which playlist on YouTube should I refer to?'},
  {'text': 'It depends on your background and previous experience with modules. It is expected to require about 5 - 15 hours per week. [source1] [source2]\nYou can also calculate it yourself using this data and then update this answer.',
   'section': 'General course-related questions',
   'question': 'Course - \u200b\u200bHow many hours per week am I expected to spend on this  course?'},
  {'text': "No, you can only get a certificate if you finish the course with a “live” cohort. We don't award certificates for the self-paced mode. The reason is you need to peer-review capstone(s) after submitting a project. You can only peer-review projects at the time the course is running.",
   'section': 'General course-related questions',
   'question': 'Certificate - Can I follow the course in a self-paced mode and get a certificate?'},
  {'text': 'The zoom link is only published to instructors/presenters/TAs.\nStudents participate via Youtube Live and submit questions to Slido (link would be pinned in the chat when Alexey goes Live). The video URL should be posted in the announcements channel on Telegram & Slack before it begins. Also, you will see it live on the DataTalksClub YouTube Channel.\nDon’t post your questions in chat as it would be off-screen before the instructors/moderators have a chance to answer it if the room is very active.',
   'section': 'General course-related questions',
   'question': 'Office Hours - What is the video/zoom link to the stream for the “Office Hour” or workshop sessions?'},
  {'text': 'Yes! Every “Office Hours” will be recorded and available a few minutes after the live session is over; so you can view (or rewatch) whenever you want.',
   'section': 'General course-related questions',
   'question': 'Office Hours - I can’t attend the “Office hours” / workshop, will it be recorded?'},
  {'text': 'You can find the latest and up-to-date deadlines here: https://docs.google.com/spreadsheets/d/e/2PACX-1vQACMLuutV5rvXg5qICuJGL-yZqIV0FBD84CxPdC5eZHf8TfzB-CJT_3Mo7U7oGVTXmSihPgQxuuoku/pubhtml\nAlso, take note of Announcements from @Au-Tomator for any extensions or other news. Or, the form may also show the updated deadline, if Instructor(s) has updated it.',
   'section': 'General course-related questions',
   'question': 'Homework - What are homework and project deadlines?'},
  {'text': 'No, late submissions are not allowed. But if the form is still not closed and it’s after the due date, you can still submit the homework. confirm your submission by the date-timestamp on the Course page.y\nOlder news:[source1] [source2]',
   'section': 'General course-related questions',
   'question': 'Homework - Are late submissions of homework allowed?'},
  {'text': 'Answer: In short, it’s your repository on github, gitlab, bitbucket, etc\nIn long, your repository or any other location you have your code where a reasonable person would look at it and think yes, you went through the week and exercises.',
   'section': 'General course-related questions',
   'question': 'Homework - What is the homework URL in the homework link?'},
  {'text': 'After you submit your homework it will be graded based on the amount of questions in a particular homework. You can see how many points you have right on the page of the homework up top. Additionally in the leaderboard you will find the sum of all points you’ve earned - points for Homeworks, FAQs and Learning in Public. If homework is clear, others work as follows: if you submit something to FAQ, you get one point, for each learning in a public link you get one point.\n(https://datatalks-club.slack.com/archives/C01FABYF2RG/p1706846846359379?thread_ts=1706825019.546229&cid=C01FABYF2RG)',
   'section': 'General course-related questions',
   'question': 'Homework and Leaderboard - what is the system for points in the course management platform?'},
  {'text': 'When you set up your account you are automatically assigned a random name such as “Lucid Elbakyan” for example. If you want to see what your Display name is.\nGo to the Homework submission link →  https://courses.datatalks.club/de-zoomcamp-2024/homework/hw2 - Log in > Click on ‘Data Engineering Zoom Camp 2024’ > click on ‘Edit Course Profile’ - your display name is here, you can also change it should you wish:',
   'section': 'General course-related questions',
   'question': 'Leaderboard - I am not on the leaderboard / how do I know which one I am on the leaderboard?'},
  {'text': 'Yes, for simplicity (of troubleshooting against the recorded videos) and stability. [source]\nBut Python 3.10 and 3.11 should work fine.',
   'section': 'General course-related questions',
   'question': 'Environment - Is Python 3.9 still the recommended version to use in 2024?'},
  {'text': 'You can set it up on your laptop or PC if you prefer to work locally from your laptop or PC.\nYou might face some challenges, especially for Windows users. If you face cnd2\nIf you prefer to work on the local machine, you may start with the week 1 Introduction to Docker and follow through.\nHowever, if you prefer to set up a virtual machine, you may start with these first:\nUsing GitHub Codespaces\nSetting up the environment on a cloudV Mcodespace\nI decided to work on a virtual machine because I have different laptops & PCs for my home & office, so I can work on this boot camp virtually anywhere.',
   'section': 'General course-related questions',
   'question': 'Environment - Should I use my local machine, GCP, or GitHub Codespaces for my environment?'},
  {'text': 'GitHub Codespaces offers you computing Linux resources with many pre-installed tools (Docker, Docker Compose, Python).\nYou can also open any GitHub repository in a GitHub Codespace.',
   'section': 'General course-related questions',
   'question': 'Environment - Is GitHub codespaces an alternative to using cli/git bash to ingest the data and create a docker file?'},
  {'text': "It's up to you which platform and environment you use for the course.\nGithub codespaces or GCP VM are just possible options, but you can do the entire course from your laptop.",
   'section': 'General course-related questions',
   'question': 'Environment - Do we really have to use GitHub codespaces? I already have PostgreSQL & Docker installed.'},
  {'text': 'Choose the approach that aligns the most with your idea for the end project\nOne of those should suffice. However, BigQuery, which is part of GCP, will be used, so learning that is probably a better option. Or you can set up a local environment for most of this course.',
   'section': 'General course-related questions',
   'question': 'Environment - Do I need both GitHub Codespaces and GCP?'},
  {'text': '1. To open Run command window, you can either:\n(1-1) Use the shortcut keys: \'Windows + R\', or\n(1-2) Right Click "Start", and click "Run" to open.\n2. Registry Values Located in Registry Editor, to open it: Type \'regedit\' in the Run command window, and then press Enter.\' 3. Now you can change the registry values "Autorun" in "HKEY_CURRENT_USER\\Software\\Microsoft\\Command Processor" from "if exists" to a blank.\nAlternatively, You can simplify the solution by deleting the fingerprint saved within the known_hosts file. In Windows, this file is placed at  C:\\Users\\<your_user_name>\\.ssh\\known_host',
   'section': 'General course-related questions',
   'question': 'This happens when attempting to connect to a GCP VM using VSCode on a Windows machine. Changing registry value in registry editor'},
  {'text': 'For uniformity at least, but you’re not restricted to GCP, you can use other cloud platforms like AWS if you’re comfortable with other cloud platforms, since you get every service that’s been provided by GCP in Azure and AWS or others..\nBecause everyone has a google account, GCP has a free trial period and gives $300 in credits  to new users. Also, we are working with BigQuery, which is a part of GCP.\nNote that to sign up for a free GCP account, you must have a valid credit card.',
   'section': 'General course-related questions',
   'question': 'Environment - Why are we using GCP and not other cloud providers?'},
  {'text': 'No, if you use GCP and take advantage of their free trial.',
   'section': 'General course-related questions',
   'question': 'Should I pay for cloud services?'},
  {'text': 'You can do most of the course without a cloud. Almost everything we use (excluding BigQuery) can be run locally. We won’t be able to provide guidelines for some things, but most of the materials are runnable without GCP.\nFor everything in the course, there’s a local alternative. You could even do the whole course locally.',
   'section': 'General course-related questions',
   'question': 'Environment - The GCP and other cloud providers are unavailable in some countries. Is it possible to provide a guide to installing a home lab?'},
  {'text': 'Yes, you can. Just remember to adapt all the information on the videos to AWS. Besides, the final capstone will be evaluated based on the task: Create a data pipeline! Develop a visualisation!\nThe problem would be when you need help. You’d need to rely on  fellow coursemates who also use AWS (or have experience using it before), which might be in smaller numbers than those learning the course with GCP.\nAlso see Is it possible to use x tool instead of the one tool you use?',
   'section': 'General course-related questions',
   'question': 'Environment - I want to use AWS. May I do that?'},
  {'text': 'We will probably have some calls during the Capstone period to clear some questions but it will be announced in advance if that happens.',
   'section': 'General course-related questions',
   'question': 'Besides the “Office Hour” which are the live zoom calls?'},
  {'text': 'We will use the same data, as the project will essentially remain the same as last year’s. The data is available here',
   'section': 'General course-related questions',
   'question': 'Are we still using the NYC Trip data for January 2021? Or are we using the 2022 data?'},
  {'text': 'No, but we moved the 2022 stuff here',
   'section': 'General course-related questions',
   'question': 'Is the 2022 repo deleted?'},
  {'text': 'Yes, you can use any tool you want for your project.',
   'section': 'General course-related questions',
   'question': 'Can I use Airflow instead for my final project?'},
  {'text': 'Yes, this applies if you want to use Airflow or Prefect instead of Mage, AWS or Snowflake instead of GCP products or Tableau instead of Metabase or Google data studio.\nThe course covers 2 alternative data stacks, one using GCP and one using local installation of everything. You can use one of them or use your tool of choice.\nShould you consider it instead of the one tool you use? That we can’t support you if you choose to use a different stack, also you would need to explain the different choices of tool for the peer review of your capstone project.',
   'section': 'General course-related questions',
   'question': 'Is it possible to use tool “X” instead of the one tool you use in the course?'},
  {'text': 'Star the repo! Share it with friends if you find it useful ❣️\nCreate a PR if you see you can improve the text or the structure of the repository.',
   'section': 'General course-related questions',
   'question': 'How can we contribute to the course?'},
  {'text': 'Yes! Linux is ideal but technically it should not matter. Students last year used all 3 OSes successfully',
   'section': 'General course-related questions',
   'question': 'Environment - Is the course [Windows/mac/Linux/...] friendly?'},
  {'text': "Have no idea how past cohorts got past this as I haven't read old slack messages, and no FAQ entries that I can find.\nLater modules (module-05 & RisingWave workshop) use shell scripts in *.sh files and most Windows users not using WSL would hit a wall and cannot continue, even in git bash or MINGW64. This is why WSL environment setup is recommended from the start.",
   'section': 'General course-related questions',
   'question': 'Environment - Roadblock for Windows users in modules with *.sh (shell scripts).'},
  {'text': 'Yes to both! check out this document: https://github.com/DataTalksClub/data-engineering-zoomcamp/blob/main/awesome-data-engineering.md',
   'section': 'General course-related questions',
   'question': 'Any books or additional resources you recommend?'},
  {'text': 'You will have two attempts for a project. If the first project deadline is over and you’re late or you submit the project and fail the first attempt, you have another chance to submit the project with the second attempt.',
   'section': 'General course-related questions',
   'question': 'Project - What is Project Attemp #1 and Project Attempt #2 exactly?'},

In [49]:
documents = []

In [50]:
for course in documents_raw:
    course_name = course['course']
    if course_name != 'machine-learning-zoomcamp':
        continue

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

In [51]:
len(documents)

375

In [52]:
documents[0]

{'text': 'Machine Learning Zoomcamp FAQ\nThe purpose of this document is to capture frequently asked technical questions.\nWe did this for our data engineering course and it worked quite well. Check this document for inspiration on how to structure your questions and answers:\nData Engineering Zoomcamp FAQ\nIn the course GitHub repository there’s a link. Here it is: https://airtable.com/shryxwLd0COOEaqXo\nwork',
 'section': 'General course-related questions',
 'question': 'How do I sign up?',
 'course': 'machine-learning-zoomcamp'}

In [53]:
texts = [doc['question'] + ' ' + doc['text'] for doc in documents]

In [54]:
texts[0]

'How do I sign up? Machine Learning Zoomcamp FAQ\nThe purpose of this document is to capture frequently asked technical questions.\nWe did this for our data engineering course and it worked quite well. Check this document for inspiration on how to structure your questions and answers:\nData Engineering Zoomcamp FAQ\nIn the course GitHub repository there’s a link. Here it is: https://airtable.com/shryxwLd0COOEaqXo\nwork'

In [55]:
embedding_model_small = TextEmbedding("BAAI/bge-small-en")

ValueError: Could not find config.json in C:\Users\felix\AppData\Local\Temp\fastembed_cache\models--Qdrant--bge-small-en\snapshots\8791246cc2a79c7949a4dc0d4a018cbd7d024879

In [56]:
from fastembed import TextEmbedding

models = TextEmbedding.list_supported_models()
len(models)

30

In [57]:
[m for m in models if "bge-small-en" in m["model"]]

[{'model': 'BAAI/bge-small-en',
  'sources': {'hf': 'Qdrant/bge-small-en',
   'url': 'https://storage.googleapis.com/qdrant-fastembed/BAAI-bge-small-en.tar.gz',
   '_deprecated_tar_struct': True},
  'model_file': 'model_optimized.onnx',
  'description': 'Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: necessary, 2023 year.',
  'license': 'mit',
  'size_in_GB': 0.13,
  'additional_files': [],
  'dim': 384,
  'tasks': {}},
 {'model': 'BAAI/bge-small-en-v1.5',
  'sources': {'hf': 'qdrant/bge-small-en-v1.5-onnx-q',
   'url': None,
   '_deprecated_tar_struct': False},
  'model_file': 'model_optimized.onnx',
  'description': 'Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: not so necessary, 2023 year.',
  'license': 'mit',
  'size_in_GB': 0.067,
  'additional_files': [],
  'dim': 384,
  'tasks': {}}]

In [58]:
Remove-Item -Recurse -Force "$env:LOCALAPPDATA\Temp\fastembed_cache\models--Qdrant--bge-small-en"

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
C:\Users\felix\AppData\Local\Temp\ipykernel_19044\2709732197.py:1: SyntaxWarning: invalid escape sequence '\T'
  Remove-Item -Recurse -Force "$env:LOCALAPPDATA\Temp\fastembed_cache\models--Qdrant--bge-small-en"

SyntaxError: invalid syntax (2709732197.py, line 1)

In [59]:
import os
import shutil

cache_path = os.path.expandvars(r"%LOCALAPPDATA%\Temp\fastembed_cache\models--Qdrant--bge-small-en")

if os.path.exists(cache_path):
    shutil.rmtree(cache_path)
    print("Cache supprimé :", cache_path)
else:
    print("Dossier introuvable :", cache_path)

Cache supprimé : C:\Users\felix\AppData\Local\Temp\fastembed_cache\models--Qdrant--bge-small-en

In [60]:
embedding_model_small = TextEmbedding("BAAI/bge-small-en")

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

In [61]:
query_vector_small = list(embedding_model_small.embed([query]))[0]
len(query_vector_small)

384

In [62]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams

ModuleNotFoundError: No module named 'qdrant_client'

In [63]:
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[62], line 1
----> 1 from qdrant_client import QdrantClient
      2 from qdrant_client.models import Distance, VectorParams

ModuleNotFoundError: No module named 'qdrant_client'

SyntaxError: invalid syntax (2768729068.py, line 1)

In [64]:
import sys
!{sys.executable} -m pip install qdrant-client

Collecting qdrant-client
  Using cached qdrant_client-1.17.1-py3-none-any.whl.metadata (11 kB)
Collecting grpcio>=1.41.0 (from qdrant-client)
  Using cached grpcio-1.80.0-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: httpx>=0.20.0 in .\.venv\Lib\site-packages (from httpx[http2]>=0.20.0->qdrant-client) (0.28.1)
Requirement already satisfied: numpy>=2.1.0 in .\.venv\Lib\site-packages (from qdrant-client) (2.4.4)
Collecting portalocker<4.0,>=2.7.0 (from qdrant-client)
  Using cached portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: protobuf>=3.20.0 in .\.venv\Lib\site-packages (from qdrant-client) (7.34.1)
Collecting pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8 (from qdrant-client)
  Using cached pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Requirement already satisfied: urllib3<3,>=1.26.14 in .\.venv\Lib\site-packages (from qdrant-client) (2.6.3)
Collecting pywin32>=226 (from portalocker<4.0,>=2.7.0->qdrant-client)
  Using cached pywin32-311-cp313-cp313-win_amd64.whl.metadata (10 kB)
Requirement already satisfied: typing-extensions~=4.12 in .\.venv\Lib\site-packages (from grpcio>=1.41.0->qdrant-client) (4.15.0)
Requirement already satisfied: anyio in .\.venv\Lib\site-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (4.13.0)
Requirement already satisfied: certifi in .\.venv\Lib\site-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (2026.2.25)
Requirement already satisfied: httpcore==1.* in .\.venv\Lib\site-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (1.0.9)
Requirement already satisfied: idna in .\.venv\Lib\site-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (3.11)
Requirement already satisfied: h11>=0.16 in .\.venv\Lib\site-packages (from httpcore==1.*->httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (0.16.0)
Collecting h2<5,>=3 (from httpx[http2]>=0.20.0->qdrant-client)
  Using cached h2-4.3.0-py3-none-any.whl.metadata (5.1 kB)
Collecting hyperframe<7,>=6.1 (from h2<5,>=3->httpx[http2]>=0.20.0->qdrant-client)
  Using cached hyperframe-6.1.0-py3-none-any.whl.metadata (4.3 kB)
Collecting hpack<5,>=4.1 (from h2<5,>=3->httpx[http2]>=0.20.0->qdrant-client)
  Using cached hpack-4.1.0-py3-none-any.whl.metadata (4.6 kB)
Collecting annotated-types>=0.6.0 (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant-client)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant-client)
  Using cached pydantic_core-2.41.5-cp313-cp313-win_amd64.whl.metadata (7.4 kB)
Collecting typing-inspection>=0.4.2 (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant-client)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Using cached qdrant_client-1.17.1-py3-none-any.whl (389 kB)
Using cached portalocker-3.2.0-py3-none-any.whl (22 kB)
Using cached grpcio-1.80.0-cp313-cp313-win_amd64.whl (4.9 MB)
Using cached h2-4.3.0-py3-none-any.whl (61 kB)
Using cached hpack-4.1.0-py3-none-any.whl (34 kB)
Using cached hyperframe-6.1.0-py3-none-any.whl (13 kB)
Using cached pydantic-2.12.5-py3-none-any.whl (463 kB)
Using cached pydantic_core-2.41.5-cp313-cp313-win_amd64.whl (2.0 MB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached pywin32-311-cp313-cp313-win_amd64.whl (9.5 MB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Installing collected packages: pywin32, typing-inspection, pydantic-core, portalocker, hyperframe, hpack, grpcio, annotated-types, pydantic, h2, qdrant-client

   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   ----------------------------------------  0/11 [pywin32]
   --- ------------------------------------  1/11 [typing-inspection]
   ---------- -----------------------------  3/11 [portalocker]
   ---------- -----------------------------  3/11 [portalocker]
   ------------------ ---------------------  5/11 [hpack]
   ------------------ ---------------------  5/11 [hpack]
   --------------------- ------------------  6/11 [grpcio]
   --------------------- ------------------  6/11 [grpcio]
   --------------------- ------------------  6/11 [grpcio]
   --------------------- ------------------  6/11 [grpcio]
   --------------------- ------------------  6/11 [grpcio]
   --------------------- ------------------  6/11 [grpcio]
   --------------------- ------------------  6/11 [grpcio]
   --------------------- ------------------  6/11 [grpcio]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   ----------------------------- ----------  8/11 [pydantic]
   -------------------------------- -------  9/11 [h2]
   -------------------------------- -------  9/11 [h2]
   -------------------------------- -------  9/11 [h2]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ------------------------------------ --- 10/11 [qdrant-client]
   ---------------------------------------- 11/11 [qdrant-client]

Successfully installed annotated-types-0.7.0 grpcio-1.80.0 h2-4.3.0 hpack-4.1.0 hyperframe-6.1.0 portalocker-3.2.0 pydantic-2.12.5 pydantic-core-2.41.5 pywin32-311 qdrant-client-1.17.1 typing-inspection-0.4.2

In [65]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams

In [66]:
client = QdrantClient(":memory:")

In [67]:
client.create_collection(
    collection_name="ml_zoomcamp",
    vectors_config=VectorParams(
        size=384,
        distance=Distance.COSINE
    )
)

True

In [68]:
points = []

for idx, (doc, vector) in enumerate(zip(documents, doc_vectors)):
    points.append({
        "id": idx,
        "vector": vector,
        "payload": doc
    })

In [69]:
client.upsert(
    collection_name="ml_zoomcamp",
    points=points
)

AttributeError: 'dict' object has no attribute 'id'

In [70]:
from qdrant_client.models import PointStruct

In [71]:
points = []

for idx, (doc, vector) in enumerate(zip(documents, doc_vectors)):
    points.append(
        PointStruct(
            id=idx,
            vector=vector.tolist(),
            payload=doc
        )
    )

In [72]:
client.upsert(
    collection_name="ml_zoomcamp",
    points=points
)

ValueError: could not broadcast input array from shape (512,) into shape (384,)

In [73]:
len(doc_vectors[0])

512

In [74]:
embedding_model_small

In [75]:
doc_vectors_small = list(embedding_model_small.embed(texts))

In [76]:
len(doc_vectors_small), len(doc_vectors_small[0])

(375, 384)

In [77]:
from qdrant_client.models import PointStruct

points = []

for idx, (doc, vector) in enumerate(zip(documents, doc_vectors_small)):
    points.append(
        PointStruct(
            id=idx,
            vector=vector.tolist(),
            payload=doc
        )
    )

In [78]:
client.upsert(
    collection_name="ml_zoomcamp",
    points=points
)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [79]:
client.delete_collection("ml_zoomcamp")

True

In [80]:
client.create_collection(
    collection_name="ml_zoomcamp",
    vectors_config=VectorParams(
        size=384,
        distance=Distance.COSINE
    )
)

True

In [81]:
len(points), type(points[0]), len(points[0].vector)

(375, qdrant_client.http.models.models.PointStruct, 384)

In [82]:
client.upsert(
    collection_name="ml_zoomcamp",
    points=points
)

UpdateResult(operation_id=0, status=<UpdateStatus.COMPLETED: 'completed'>)

In [83]:
query = "I just discovered the course. Can I join now?"

In [84]:
query_vector_small = list(embedding_model_small.embed([query]))[0]

In [85]:
len(query_vector_small)

384

In [86]:
results = client.search(
    collection_name="ml_zoomcamp",
    query_vector=query_vector_small.tolist(),
    limit=5
)

AttributeError: 'QdrantClient' object has no attribute 'search'

In [87]:
results = client.query_points(
    collection_name="ml_zoomcamp",
    query=query_vector_small.tolist(),
    limit=5
)

In [88]:
results

QueryResponse(points=[ScoredPoint(id=14, version=0, score=0.8703173344744922, payload={'text': 'Yes, you can. You won’t be able to submit some of the homeworks, but you can still take part in the course.\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers’ Projects by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.', 'section': 'General course-related questions', 'question': 'The course has already started. Can I still join it?', 'course': 'machine-learning-zoomcamp'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=6, version=0, score=0.8691884799206437, payload={'text': 'Approximately 4 months, but may take more if you want to do some extra activities (an extra project, an article, etc)', 'section': 'General course-related questions', 'question': 'How long is the course?', 'course': 'machine-learning-zoomcamp'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=13, version=0, score=0.8683312064803744, payload={'text': "Here’s how you join a in Slack: https://slack.com/help/articles/205239967-Join-a-channel\nClick “All channels” at the top of your left sidebar. If you don't see this option, click “More” to find it.\nBrowse the list of public channels in your workspace, or use the search bar to search by channel name or description.\nSelect a channel from the list to view it.\nClick Join Channel.\nDo we need to provide the GitHub link to only our code corresponding to the homework questions?\nYes. You are required to provide the URL to your repo in order to receive a grade", 'section': 'General course-related questions', 'question': 'I’m new to Slack and can’t find the course channel. Where is it?', 'course': 'machine-learning-zoomcamp'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=293, version=0, score=0.8576106482659016, payload={'text': 'TODO', 'section': '10. Kubernetes and TensorFlow Serving', 'question': 'How to get started with Week 10?', 'course': 'machine-learning-zoomcamp'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=17, version=0, score=0.8571540170407861, payload={'text': 'Welcome to the course! Go to the course page (http://mlzoomcamp.com/), scroll down and start going through the course materials. Then read everything in the cohort folder for your cohort’s year.\nClick on the links and start watching the videos. Also watch office hours from previous cohorts. Go to DTC youtube channel and click on Playlists and search for {course yyyy}. ML Zoomcamp was first launched in 2021.\nOr you can just use this link: http://mlzoomcamp.com/#syllabus', 'section': 'General course-related questions', 'question': 'I just joined. What should I do next? How can I access course materials?', 'course': 'machine-learning-zoomcamp'}, vector=None, shard_key=None, order_value=None)])

In [89]:
import hashlib

def generate_id(doc):
    text = doc['course'] + doc['question'] + doc['text']
    return hashlib.md5(text.encode()).hexdigest()[:8]

for doc in documents:
    doc['id'] = generate_id(doc)

In [90]:
from collections import defaultdict

hashes = defaultdict(list)

for doc in documents:
    doc_id = doc['id']
    hashes[doc_id].append(doc)

len(hashes), len(documents)

(375, 375)

In [91]:
import json

with open('documents-with-ids.json', 'w') as f_out:
    json.dump(documents, f_out, indent=2)

In [92]:
prompt_template = """
You emulate a student who is taking our course.
Formulate 5 questions this student might ask based on the provided FAQ record.

The record should contain the answer to the questions, and the questions should be complete and not too short.
If possible, use as few words as possible from the record.

FAQ record:
course: {course}
section: {section}
question: {question}
answer: {text}

Provide the output in parsable JSON without using code blocks.
""".strip()

In [93]:
prompt = prompt_template.format(**documents[0])
print(prompt)

You emulate a student who is taking our course.
Formulate 5 questions this student might ask based on the provided FAQ record.

The record should contain the answer to the questions, and the questions should be complete and not too short.
If possible, use as few words as possible from the record.

FAQ record:
course: machine-learning-zoomcamp
section: General course-related questions
question: How do I sign up?
answer: Machine Learning Zoomcamp FAQ
The purpose of this document is to capture frequently asked technical questions.
We did this for our data engineering course and it worked quite well. Check this document for inspiration on how to structure your questions and answers:
Data Engineering Zoomcamp FAQ
In the course GitHub repository there’s a link. Here it is: https://airtable.com/shryxwLd0COOEaqXo
work

Provide the output in parsable JSON without using code blocks.

In [94]:
import os
from openai import OpenAI

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

ModuleNotFoundError: No module named 'openai'

In [95]:
!pip install openai

Collecting openai
  Using cached openai-2.30.0-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in .\.venv\Lib\site-packages (from openai) (4.13.0)
Collecting distro<2,>=1.7.0 (from openai)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in .\.venv\Lib\site-packages (from openai) (0.28.1)
Collecting jiter<1,>=0.10.0 (from openai)
  Using cached jiter-0.13.0-cp313-cp313-win_amd64.whl.metadata (5.3 kB)
Requirement already satisfied: pydantic<3,>=1.9.0 in .\.venv\Lib\site-packages (from openai) (2.12.5)
Collecting sniffio (from openai)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: tqdm>4 in .\.venv\Lib\site-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in .\.venv\Lib\site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in .\.venv\Lib\site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in .\.venv\Lib\site-packages (from httpx<1,>=0.23.0->openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in .\.venv\Lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in .\.venv\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in .\.venv\Lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in .\.venv\Lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in .\.venv\Lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: colorama in .\.venv\Lib\site-packages (from tqdm>4->openai) (0.4.6)
Using cached openai-2.30.0-py3-none-any.whl (1.1 MB)
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Using cached jiter-0.13.0-cp313-cp313-win_amd64.whl (202 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Installing collected packages: sniffio, jiter, distro, openai

   -------------------- ------------------- 2/4 [distro]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ------------------------------ --------- 3/4 [openai]
   ---------------------------------------- 4/4 [openai]

Successfully installed distro-1.9.0 jiter-0.13.0 openai-2.30.0 sniffio-1.3.1

In [96]:
import os
from openai import OpenAI

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
print(client)

OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

In [97]:
import os
print(os.getenv("OPENAI_API_KEY"))

None

In [1]:
import os
print(os.getenv("OPENAI_API_KEY") is not None)

True

In [2]:
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

response_text = response.choices[0].message.content
print(response_text)

NameError: name 'client' is not defined

In [3]:
import os
from openai import OpenAI

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

In [4]:
print(prompt[:200])

NameError: name 'prompt' is not defined

In [5]:
prompt_template = """
You emulate a student who is taking our course.
Formulate 5 questions this student might ask based on the provided FAQ record.

The record should contain the answer to the questions, and the questions should be complete and not too short.
If possible, use as few words as possible from the record.

FAQ record:
course: {course}
section: {section}
question: {question}
answer: {text}

Provide the output in parsable JSON without using code blocks.
""".strip()

prompt = prompt_template.format(**documents[0])

NameError: name 'documents' is not defined

In [6]:
import json

with open("documents-with-ids.json", "r") as f_in:
    documents = json.load(f_in)

In [7]:
len(documents)

375

In [8]:
print(response_text)

NameError: name 'response_text' is not defined

In [9]:
import json

questions = json.loads(response_text)
questions

NameError: name 'response_text' is not defined

In [10]:
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

response_text = response.choices[0].message.content
print(response_text)

NameError: name 'prompt' is not defined

In [11]:
import json
import os
from openai import OpenAI

with open("documents-with-ids.json", "r") as f_in:
    documents = json.load(f_in)

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

In [12]:
prompt_template = """
You emulate a student who is taking our course.
Formulate 5 questions this student might ask based on the provided FAQ record.

The record should contain the answer to the questions, and the questions should be complete and not too short.
If possible, use as few words as possible from the record.

FAQ record:
course: {course}
section: {section}
question: {question}
answer: {text}

Provide the output in parsable JSON without using code blocks.
""".strip()

prompt = prompt_template.format(**documents[0])
print(prompt)

You emulate a student who is taking our course.
Formulate 5 questions this student might ask based on the provided FAQ record.

The record should contain the answer to the questions, and the questions should be complete and not too short.
If possible, use as few words as possible from the record.

FAQ record:
course: machine-learning-zoomcamp
section: General course-related questions
question: How do I sign up?
answer: Machine Learning Zoomcamp FAQ
The purpose of this document is to capture frequently asked technical questions.
We did this for our data engineering course and it worked quite well. Check this document for inspiration on how to structure your questions and answers:
Data Engineering Zoomcamp FAQ
In the course GitHub repository there’s a link. Here it is: https://airtable.com/shryxwLd0COOEaqXo
work

Provide the output in parsable JSON without using code blocks.

In [13]:
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

response_text = response.choices[0].message.content
print(response_text)

{
  "questions": [
    {
      "question": "What is the link to sign up for the Machine Learning Zoomcamp course?"
    },
    {
      "question": "Can you explain the purpose of the FAQ document for this course?"
    },
    {
      "question": "Where can I find inspiration for the structure of the questions and answers?"
    },
    {
      "question": "Is there a GitHub repository related to this Machine Learning course?"
    },
    {
      "question": "How did the FAQ document format work for the previous Data Engineering course?"
    }
  ]
}

In [14]:
import json

parsed = json.loads(response_text)
parsed

{'questions': [{'question': 'What is the link to sign up for the Machine Learning Zoomcamp course?'},
  {'question': 'Can you explain the purpose of the FAQ document for this course?'},
  {'question': 'Where can I find inspiration for the structure of the questions and answers?'},
  {'question': 'Is there a GitHub repository related to this Machine Learning course?'},
  {'question': 'How did the FAQ document format work for the previous Data Engineering course?'}]}

In [15]:
questions = [q["question"] for q in parsed["questions"]]
questions

['What is the link to sign up for the Machine Learning Zoomcamp course?',
 'Can you explain the purpose of the FAQ document for this course?',
 'Where can I find inspiration for the structure of the questions and answers?',
 'Is there a GitHub repository related to this Machine Learning course?',
 'How did the FAQ document format work for the previous Data Engineering course?']

In [16]:
def generate_questions(doc):
    prompt = prompt_template.format(**doc)

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    response_text = response.choices[0].message.content
    parsed = json.loads(response_text)

    questions = [q["question"] for q in parsed["questions"]]

    return questions

In [17]:
generate_questions(documents[0])

['What is the purpose of the Machine Learning Zoomcamp FAQ document?',
 'Where can I find the registration link for the Machine Learning Zoomcamp?',
 'Is there a similar FAQ document for another course?',
 'How did the inspiration for this FAQ document come about?',
 'Can I access the course GitHub repository to find more information?']

In [18]:
for doc in documents:

_IncompleteInputError: incomplete input (3565645544.py, line 1)

In [19]:
results = {}

for doc in documents:
    doc_id = doc["id"]
    questions = generate_questions(doc)
    results[doc_id] = questions

TypeError: string indices must be integers, not 'str'

In [ ]:
results = {}

for doc in documents[:3]:
    doc_id = doc["id"]
    questions = generate_questions(doc)
    results[doc_id] = questions

results

In [20]:
def generate_questions(doc):
    prompt = prompt_template.format(**doc)

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    response_text = response.choices[0].message.content
    parsed = json.loads(response_text)

    raw_questions = parsed["questions"]

    if len(raw_questions) > 0 and isinstance(raw_questions[0], dict):
        questions = [q["question"] for q in raw_questions]
    else:
        questions = raw_questions

    return questions

In [21]:
generate_questions(documents[0])

['What steps do I need to follow to register for the Machine Learning Zoomcamp?',
 'Is there a specific document that lists frequently asked questions about the course?',
 'Can I find inspiration for structuring my questions and answers somewhere?',
 'Where can I find the GitHub repository for the Machine Learning Zoomcamp?',
 'Is there a link I can access to get more information about signing up for the course?']

In [22]:
results = {}

for doc in documents[:3]:
    doc_id = doc["id"]
    questions = generate_questions(doc)
    results[doc_id] = questions

results

{'c096c9a5': ['What is the purpose of the Machine Learning Zoomcamp FAQ document?',
  'Where can I find the link to sign up for the course?',
  'Is there a similar FAQ document for other courses?',
  'How did the FAQ document work for the data engineering course?',
  'Can you provide the URL for the course GitHub repository?'],
 '8f50c962': ['Are the course lectures presented live, or can they be accessed at any time?',
  'When can I begin watching the course content, and how will I access it?',
  'Will there be any live sessions for interaction, and how often will they occur?',
  'Are the office hours sessions recorded for later viewing?',
  'Where can I find both the pre-recorded videos and office hour sessions?'],
 '3359a4df': ['What should I do if I cannot attend a live session of the machine learning course?',
  'Will I be able to access the material if I miss a class?',
  'Is it possible to ask questions after a session I missed?',
  'How can I ensure my questions are addressed during the live stream?',
  'Is there a way to ask questions outside of live sessions?']}

In [23]:
results = {}

for doc in documents:
    doc_id = doc["id"]

    if doc_id in results:
        continue

    questions = generate_questions(doc)
    results[doc_id] = questions

JSONDecodeError: Invalid control character at: line 13 column 86 (char 488)

In [ ]:
import pickle

with open("results.pkl", "wb") as f_out:
    pickle.dump(results, f_out)

In [24]:
import pickle

with open("results.pkl", "rb") as f_in:
    results = pickle.load(f_in)

FileNotFoundError: [Errno 2] No such file or directory: 'results.pkl'

In [25]:
import pickle

with open("results.pkl", "wb") as f_out:
    pickle.dump(results, f_out)

In [26]:
with open("results.pkl", "rb") as f_in:
    results = pickle.load(f_in)

In [27]:
doc_index = {doc["id"]: doc for doc in documents}

In [28]:
final_results = []

for doc_id, questions in results.items():
    doc = doc_index[doc_id]
    course = doc["course"]

    for question in questions:
        final_results.append({
            "question": question,
            "course": course,
            "document": doc_id
        })

final_results[:5]

[{'question': 'What steps should I follow to register for the Machine Learning Zoomcamp course?',
  'course': 'machine-learning-zoomcamp',
  'document': 'c096c9a5'},
 {'question': 'Where can I find the frequently asked questions for the Machine Learning Zoomcamp?',
  'course': 'machine-learning-zoomcamp',
  'document': 'c096c9a5'},
 {'question': 'Is there a specific document that contains answers to technical queries for this course?',
  'course': 'machine-learning-zoomcamp',
  'document': 'c096c9a5'},
 {'question': 'Can you direct me to the GitHub repository associated with the Machine Learning Zoomcamp?',
  'course': 'machine-learning-zoomcamp',
  'document': 'c096c9a5'},
 {'question': 'What is the purpose of the FAQ document created for this course?',
  'course': 'machine-learning-zoomcamp',
  'document': 'c096c9a5'}]

In [29]:
import pandas as pd

df_ground_truth = pd.DataFrame(final_results)
df_ground_truth.head()

,question,course,document
0,What steps should I follow to register for the...,machine-learning-zoomcamp,c096c9a5
1,Where can I find the frequently asked question...,machine-learning-zoomcamp,c096c9a5
2,Is there a specific document that contains ans...,machine-learning-zoomcamp,c096c9a5
3,Can you direct me to the GitHub repository ass...,machine-learning-zoomcamp,c096c9a5
4,What is the purpose of the FAQ document create...,machine-learning-zoomcamp,c096c9a5

In [30]:
df_ground_truth.to_csv("ground-truth-data.csv", index=False)

In [31]:
import pandas as pd

df_ground_truth = pd.read_csv("ground-truth-data.csv")
df_ground_truth.head()

,question,course,document
0,What steps should I follow to register for the...,machine-learning-zoomcamp,c096c9a5
1,Where can I find the frequently asked question...,machine-learning-zoomcamp,c096c9a5
2,Is there a specific document that contains ans...,machine-learning-zoomcamp,c096c9a5
3,Can you direct me to the GitHub repository ass...,machine-learning-zoomcamp,c096c9a5
4,What is the purpose of the FAQ document create...,machine-learning-zoomcamp,c096c9a5

In [32]:
ground_truth = df_ground_truth.to_dict(orient="records")
ground_truth[:3]

[{'question': 'What steps should I follow to register for the Machine Learning Zoomcamp course?',
  'course': 'machine-learning-zoomcamp',
  'document': 'c096c9a5'},
 {'question': 'Where can I find the frequently asked questions for the Machine Learning Zoomcamp?',
  'course': 'machine-learning-zoomcamp',
  'document': 'c096c9a5'},
 {'question': 'Is there a specific document that contains answers to technical queries for this course?',
  'course': 'machine-learning-zoomcamp',
  'document': 'c096c9a5'}]

In [33]:
q = ground_truth[0]

query = q["question"]
course = q["course"]

query, course

('What steps should I follow to register for the Machine Learning Zoomcamp course?',
 'machine-learning-zoomcamp')

In [34]:
results = search(query, course)
results[:3]

NameError: name 'search' is not defined

In [35]:
import minsearch

index = minsearch.Index(
    text_fields=["question", "text", "section"],
    keyword_fields=["course", "id"]
)

index.fit(documents)

ModuleNotFoundError: No module named 'minsearch'

In [36]:
import sys
!{sys.executable} -m pip install minsearch

Collecting minsearch
  Using cached minsearch-0.0.10-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from minsearch) (2.3.2)
Requirement already satisfied: pandas in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from minsearch) (2.3.2)
Requirement already satisfied: scikit-learn in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from minsearch) (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from pandas->minsearch) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from pandas->minsearch) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from pandas->minsearch) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas->minsearch) (1.17.0)
Requirement already satisfied: scipy>=1.10.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn->minsearch) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn->minsearch) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn->minsearch) (3.6.0)
Using cached minsearch-0.0.10-py3-none-any.whl (33 kB)
Installing collected packages: minsearch
Successfully installed minsearch-0.0.10

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [37]:
import minsearch

In [38]:
import minsearch

index = minsearch.Index(
    text_fields=["question", "text", "section"],
    keyword_fields=["course", "id"]
)

index.fit(documents)

In [39]:
def search(query, course):
    boost = {
        "question": 3.0,
        "text": 1.0,
        "section": 0.5
    }

    results = index.search(
        query=query,
        filter_dict={"course": course},
        boost_dict=boost,
        num_results=5
    )

    return results

In [40]:
q = ground_truth[0]

query = q["question"]
course = q["course"]

results = search(query, course)

results[:3]

[{'text': 'I’ve seen LinkedIn users list DataTalksClub as Experience with titles as:\nMachine Learning Fellow\nMachine Learning Student\nMachine Learning Participant\nMachine Learning Trainee\nPlease note it is best advised that you do not list the experience as an official “job” or “internship” experience since DataTalksClub did not hire you, nor financially compensate you.\nOther ways you can incorporate the experience in the following sections:\nOrganizations\nProjects\nSkills\nFeatured\nOriginal posts\nCertifications\nCourses\nBy Annaliese Bronz\nInteresting question, I put the link of my project into my CV as showcase and make posts to show my progress.\nBy Ani Mkrtumyan',
  'section': 'Miscellaneous',
  'question': 'Any advice for adding the Machine Learning Zoomcamp experience to your LinkedIn profile?',
  'course': 'machine-learning-zoomcamp',
  'id': '7da6fe26'},
 {'text': 'Welcome to the course! Go to the course page (http://mlzoomcamp.com/), scroll down and start going through the course materials. Then read everything in the cohort folder for your cohort’s year.\nClick on the links and start watching the videos. Also watch office hours from previous cohorts. Go to DTC youtube channel and click on Playlists and search for {course yyyy}. ML Zoomcamp was first launched in 2021.\nOr you can just use this link: http://mlzoomcamp.com/#syllabus',
  'section': 'General course-related questions',
  'question': 'I just joined. What should I do next? How can I access course materials?',
  'course': 'machine-learning-zoomcamp',
  'id': 'b72d1144'},
 {'text': "Should we perform EDA on the base of train or train+validation or train+validation+test dataset?\nIt's indeed good practice to only rely on the train dataset for EDA. Including validation might be okay. But we aren't supposed to touch the test dataset, even just looking at it isn't a good idea. We indeed pretend that this is the future unseen data\nAlena Kniazeva",
  'section': '3. Machine Learning for Classification',
  'question': 'What data should be used for EDA?',
  'course': 'machine-learning-zoomcamp',
  'id': 'cfb64de7'}]

In [41]:
expected_doc_id = q["document"]
expected_doc_id

'c096c9a5'

In [42]:
[result["id"] for result in results]

['7da6fe26', 'b72d1144', 'cfb64de7', '054de1d0', '597a4f48']

In [43]:
expected_doc_id in [result["id"] for result in results]

False

In [44]:
relevance = [result["id"] == expected_doc_id for result in results]
relevance

[False, False, False, False, False]

In [45]:
relevance_total = []

for q in ground_truth:
    query = q["question"]
    course = q["course"]
    expected_doc_id = q["document"]

    results = search(query, course)

    relevance = [result["id"] == expected_doc_id for result in results]

    relevance_total.append(relevance)

relevance_total[:3]

[[False, False, False, False, False],
 [False, False, False, False, False],
 [False, False, False, False, False]]

In [46]:
def hit_rate(relevance_total):
    score = 0

    for line in relevance_total:
        if True in line:
            score += 1

    return score / len(relevance_total)

In [47]:
hit_rate(relevance_total)

0.7379310344827587

In [48]:
def mrr(relevance_total):
    score = 0

    for line in relevance_total:
        for rank in range(len(line)):
            if line[rank]:
                score += 1 / (rank + 1)
                break

    return score / len(relevance_total)

In [49]:
mrr(relevance_total)

0.6018390804597702

In [50]:
def evaluate(ground_truth, search):
    relevance_total = []

    for q in ground_truth:
        query = q["question"]
        course = q["course"]
        expected_doc_id = q["document"]

        results = search(query, course)

        relevance = [result["id"] == expected_doc_id for result in results]
        relevance_total.append(relevance)

    return hit_rate(relevance_total), mrr(relevance_total)

In [51]:
evaluate(ground_truth, search)

(0.7379310344827587, 0.6018390804597702)

In [52]:
import sys
!{sys.executable} -m pip install -U minsearch qdrant_client

Requirement already satisfied: minsearch in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (0.0.10)
Requirement already satisfied: qdrant_client in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (1.17.1)
Requirement already satisfied: numpy in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from minsearch) (2.3.2)
Requirement already satisfied: pandas in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from minsearch) (2.3.2)
Requirement already satisfied: scikit-learn in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from minsearch) (1.8.0)
Requirement already satisfied: grpcio>=1.41.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from qdrant_client) (1.80.0)
Requirement already satisfied: httpx>=0.20.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx[http2]>=0.20.0->qdrant_client) (0.28.1)
Requirement already satisfied: portalocker<4.0,>=2.7.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from qdrant_client) (3.2.0)
Requirement already satisfied: protobuf>=3.20.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from qdrant_client) (6.32.1)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from qdrant_client) (2.12.3)
Requirement already satisfied: urllib3<3,>=1.26.14 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from qdrant_client) (2.5.0)
Requirement already satisfied: pywin32>=226 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from portalocker<4.0,>=2.7.0->qdrant_client) (311)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from grpcio>=1.41.0->qdrant_client) (4.15.0)
Requirement already satisfied: anyio in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant_client) (4.11.0)
Requirement already satisfied: certifi in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant_client) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant_client) (1.0.9)
Requirement already satisfied: idna in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant_client) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpcore==1.*->httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant_client) (0.16.0)
Requirement already satisfied: h2<5,>=3 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx[http2]>=0.20.0->qdrant_client) (4.3.0)
Requirement already satisfied: hyperframe<7,>=6.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from h2<5,>=3->httpx[http2]>=0.20.0->qdrant_client) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from h2<5,>=3->httpx[http2]>=0.20.0->qdrant_client) (4.1.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant_client) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant_client) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant_client) (0.4.2)
Requirement already satisfied: sniffio>=1.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from anyio->httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant_client) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from pandas->minsearch) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from pandas->minsearch) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from pandas->minsearch) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas->minsearch) (1.17.0)
Requirement already satisfied: scipy>=1.10.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn->minsearch) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn->minsearch) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn->minsearch) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [53]:
import requests
import pandas as pd

url_prefix = 'https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main/03-evaluation/'
docs_url = url_prefix + 'search_evaluation/documents-with-ids.json'
documents = requests.get(docs_url).json()

ground_truth_url = url_prefix + 'search_evaluation/ground-truth-data.csv'
df_ground_truth = pd.read_csv(ground_truth_url)
ground_truth = df_ground_truth.to_dict(orient='records')

In [54]:
len(documents), len(ground_truth)

(948, 4627)

In [55]:
documents[0]
ground_truth[0]

{'question': 'When does the course begin?',
 'course': 'data-engineering-zoomcamp',
 'document': 'c02e79ef'}

In [56]:
import minsearch

index = minsearch.Index(
    text_fields=["question", "section", "text"],
    keyword_fields=["course", "id"]
)

index.fit(documents)

In [57]:
def minsearch_search(q):
    boost = {'question': 1.5, 'section': 0.1}

    results = index.search(
        query=q["question"],
        filter_dict={"course": q["course"]},
        boost_dict=boost,
        num_results=5
    )

    return results

In [58]:
evaluate(ground_truth, minsearch_search)

TypeError: minsearch_search() takes 1 positional argument but 2 were given

In [59]:
from tqdm.auto import tqdm

def hit_rate(relevance_total):
    cnt = 0

    for line in relevance_total:
        if True in line:
            cnt = cnt + 1

    return cnt / len(relevance_total)

def mrr(relevance_total):
    total_score = 0.0

    for line in relevance_total:
        for rank in range(len(line)):
            if line[rank] == True:
                total_score = total_score + 1 / (rank + 1)

    return total_score / len(relevance_total)

def evaluate(ground_truth, search_function):
    relevance_total = []

    for q in tqdm(ground_truth):
        doc_id = q['document']
        results = search_function(q)
        relevance = [d['id'] == doc_id for d in results]
        relevance_total.append(relevance)

    return {
        'hit_rate': hit_rate(relevance_total),
        'mrr': mrr(relevance_total),
    }

C:\Users\felix\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [60]:
evaluate(ground_truth, minsearch_search)

100%|█████████████████████████████████████████████████████████████████████████████| 4627/4627 [00:11<00:00, 389.45it/s]

{'hit_rate': 0.848714069591528, 'mrr': 0.7288235717887772}

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import make_pipeline

texts = []

for doc in documents:
    t = doc['question']
    texts.append(t)

pipeline = make_pipeline(
    TfidfVectorizer(min_df=3),
    TruncatedSVD(n_components=128, random_state=1)
)

X = pipeline.fit_transform(texts)

In [62]:
X.shape

(948, 128)

In [63]:
from minsearch import VectorSearch

vindex = VectorSearch(keyword_fields={'course'})
vindex.fit(X, documents)

In [64]:
def question_vector_search(q):
    question = q['question']
    course = q['course']

    v = pipeline.transform([question])[0]

    results = vindex.search(
        query_vector=v,
        filter_dict={'course': course},
        num_results=5
    )

    return results

In [65]:
evaluate(ground_truth, question_vector_search)

100%|█████████████████████████████████████████████████████████████████████████████| 4627/4627 [00:08<00:00, 515.55it/s]

{'hit_rate': 0.48173762697212014, 'mrr': 0.3572833369353793}

In [66]:
texts = []

for doc in documents:
    t = doc['question'] + ' ' + doc['text']
    texts.append(t)

In [67]:
"How do I sign up? Machine Learning Zoomcamp FAQ ..."

'How do I sign up? Machine Learning Zoomcamp FAQ ...'

In [68]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import make_pipeline

pipeline = make_pipeline(
    TfidfVectorizer(min_df=3),
    TruncatedSVD(n_components=128, random_state=1)
)

X = pipeline.fit_transform(texts)
X.shape

(948, 128)

In [69]:
from minsearch import VectorSearch

vindex = VectorSearch(keyword_fields={'course'})
vindex.fit(X, documents)

In [70]:
def question_text_vector_search(q):
    question = q['question']
    course = q['course']

    v = pipeline.transform([question])[0]

    results = vindex.search(
        query_vector=v,
        filter_dict={'course': course},
        num_results=5
    )

    return results

In [71]:
evaluate(ground_truth, question_text_vector_search)

100%|█████████████████████████████████████████████████████████████████████████████| 4627/4627 [00:11<00:00, 404.40it/s]

{'hit_rate': 0.8210503566025502, 'mrr': 0.6717347453353508}

In [72]:
texts = []

for doc in documents:
    text = doc['question'] + ' ' + doc['text']
    texts.append(text)

In [73]:
from qdrant_client import QdrantClient

client = QdrantClient(":memory:")

In [74]:
client.create_collection(
    collection_name="hw4-question-text",
    vectors_config={
        "size": 512,
        "distance": "Cosine"
    }
)

True

In [75]:
from qdrant_client.models import PointStruct
from sentence_transformers import SentenceTransformer

model_handle = "jinaai/jina-embeddings-v2-small-en"
embedding_model = SentenceTransformer(model_handle)

vectors = embedding_model.encode(texts, show_progress_bar=True)

ModuleNotFoundError: No module named 'sentence_transformers'

In [76]:
import sys
!{sys.executable} -m pip install sentence-transformers

Collecting sentence-transformers
  Downloading sentence_transformers-5.3.0-py3-none-any.whl.metadata (16 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-5.4.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (1.8.0)
Collecting torch>=1.11.0 (from sentence-transformers)
  Downloading torch-2.11.0-cp313-cp313-win_amd64.whl.metadata (29 kB)
Requirement already satisfied: numpy in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (2.3.2)
Requirement already satisfied: scikit-learn in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: scipy in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: packaging>=20.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Collecting regex>=2025.10.22 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached regex-2026.3.32-cp313-cp313-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.1)
Collecting safetensors>=0.4.3 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: filelock>=3.10.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2026.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.11.0)
Requirement already satisfied: certifi in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Collecting setuptools<82 (from torch>=1.11.0->sentence-transformers)
  Downloading setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: sympy>=1.13.3 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: joblib>=1.3.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: click>=8.2.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.3.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Downloading sentence_transformers-5.3.0-py3-none-any.whl (512 kB)
Downloading transformers-5.4.0-py3-none-any.whl (10.1 MB)
   ---------------------------------------- 0.0/10.1 MB ? eta -:--:--
   ------------------- -------------------- 5.0/10.1 MB 23.8 MB/s eta 0:00:01
   ---------------------------------------  10.0/10.1 MB 24.4 MB/s eta 0:00:01
   ---------------------------------------- 10.1/10.1 MB 23.4 MB/s  0:00:00
Using cached regex-2026.3.32-cp313-cp313-win_amd64.whl (277 kB)
Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl (341 kB)
Downloading torch-2.11.0-cp313-cp313-win_amd64.whl (114.6 MB)
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
   - -------------------------------------- 5.0/114.6 MB 26.9 MB/s eta 0:00:05
   --- ------------------------------------ 10.0/114.6 MB 24.2 MB/s eta 0:00:05
   ----- ---------------------------------- 14.9/114.6 MB 24.0 MB/s eta 0:00:05
   ------- -------------------------------- 20.7/114.6 MB 25.2 MB/s eta 0:00:04
   --------- ------------------------------ 26.5/114.6 MB 25.8 MB/s eta 0:00:04
   ----------- ---------------------------- 32.2/114.6 MB 26.1 MB/s eta 0:00:04
   ------------- -------------------------- 38.5/114.6 MB 26.5 MB/s eta 0:00:03
   --------------- ------------------------ 44.3/114.6 MB 26.8 MB/s eta 0:00:03
   ----------------- ---------------------- 50.1/114.6 MB 27.0 MB/s eta 0:00:03
   ------------------- -------------------- 56.1/114.6 MB 27.2 MB/s eta 0:00:03
   --------------------- ------------------ 61.6/114.6 MB 27.4 MB/s eta 0:00:02
   ----------------------- ---------------- 66.8/114.6 MB 27.1 MB/s eta 0:00:02
   ------------------------- -------------- 71.8/114.6 MB 26.9 MB/s eta 0:00:02
   --------------------------- ------------ 77.6/114.6 MB 27.0 MB/s eta 0:00:02
   ----------------------------- ---------- 83.4/114.6 MB 26.9 MB/s eta 0:00:02
   ------------------------------ --------- 88.6/114.6 MB 26.9 MB/s eta 0:00:01
   -------------------------------- ------- 94.4/114.6 MB 27.0 MB/s eta 0:00:01
   ---------------------------------- ---- 100.1/114.6 MB 27.1 MB/s eta 0:00:01
   ----------------------------------- --- 105.6/114.6 MB 27.1 MB/s eta 0:00:01
   --------------------------------------  111.7/114.6 MB 27.2 MB/s eta 0:00:01
   --------------------------------------  114.3/114.6 MB 27.2 MB/s eta 0:00:01
   ---------------------------------------- 114.6/114.6 MB 26.1 MB/s  0:00:04
Downloading setuptools-81.0.0-py3-none-any.whl (1.1 MB)
   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   ---------------------------------------- 1.1/1.1 MB 22.8 MB/s  0:00:00
Installing collected packages: setuptools, safetensors, regex, torch, transformers, sentence-transformers

  Attempting uninstall: setuptools

    Found existing installation: setuptools 82.0.1

    Uninstalling setuptools-82.0.1:

   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
      Successfully uninstalled setuptools-82.0.1
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ---------------------------------------- 0/6 [setuptools]
   ------ --------------------------------- 1/6 [safetensors]
   ------------- -------------------------- 2/6 [regex]
   ------------- -------------------------- 2/6 [regex]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]
   -------------------- ------------------- 3/6 [torch]

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [77]:
from sentence_transformers import SentenceTransformer

In [78]:
model_handle = "jinaai/jina-embeddings-v2-small-en"
embedding_model = SentenceTransformer(model_handle)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
C:\Users\felix\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\felix\.cache\huggingface\hub\models--jinaai--jina-embeddings-v2-small-en. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|███████████████████████████████████████████████████████████████| 46/46 [00:00<00:00, 2449.79it/s]
BertModel LOAD REPORT from: jinaai/jina-embeddings-v2-small-en
Key                                                  | Status     |
-----------------------------------------------------+------------+-
encoder.layer.{0, 1, 2, 3}.mlp.wo.bias               | UNEXPECTED |
encoder.layer.{0, 1, 2, 3}.mlp.gated_layers.weight   | UNEXPECTED |
encoder.layer.{0, 1, 2, 3}.mlp.layernorm.bias        | UNEXPECTED |
encoder.layer.{0, 1, 2, 3}.mlp.wo.weight             | UNEXPECTED |
encoder.layer.{0, 1, 2, 3}.mlp.layernorm.weight      | UNEXPECTED |
encoder.layer.{0, 1, 2, 3}.intermediate.dense.weight | MISSING    |
encoder.layer.{0, 1, 2, 3}.intermediate.dense.bias   | MISSING    |
encoder.layer.{0, 1, 2, 3}.output.LayerNorm.bias     | MISSING    |
encoder.layer.{0, 1, 2, 3}.output.dense.weight       | MISSING    |
encoder.layer.{0, 1, 2, 3}.output.dense.bias         | MISSING    |
encoder.layer.{0, 1, 2, 3}.output.LayerNorm.weight   | MISSING    |
embeddings.position_embeddings.weight                | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [79]:
import sys
!{sys.executable} -m pip install sentence-transformers

Requirement already satisfied: sentence-transformers in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (5.3.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (5.4.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: torch>=1.11.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (2.11.0)
Requirement already satisfied: numpy in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (2.3.2)
Requirement already satisfied: scikit-learn in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: scipy in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: packaging>=20.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.3.32)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2026.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.11.0)
Requirement already satisfied: certifi in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: setuptools<82 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: joblib>=1.3.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: click>=8.2.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.3.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [80]:
vec = embedding_model.encode("hello world")
type(vec), len(vec)

(numpy.ndarray, 512)

In [81]:
vec = embedding_model.encode("hello world")
print(type(vec))
print(len(vec))

<class 'numpy.ndarray'>
512

In [82]:
texts = []

for doc in documents:
    text = doc['question'] + ' ' + doc['text']
    texts.append(text)

vectors = embedding_model.encode(texts, show_progress_bar=True)

Batches: 100%|█████████████████████████████████████████████████████████████████████████| 30/30 [00:46<00:00,  1.56s/it]

In [83]:
from qdrant_client import QdrantClient

client = QdrantClient(":memory:")

In [ ]:
client.create_collection(
    collection_name="hw-qdrant",
    vectors_config={
        "size": 512,
        "distance": "Cosine"
    }
)

In [84]:
from qdrant_client.models import PointStruct

points = []

for i, doc in enumerate(documents):
    points.append(
        PointStruct(
            id=i,
            vector=vectors[i].tolist(),
            payload=doc
        )
    )

client.upsert(
    collection_name="hw-qdrant",
    points=points
)

ValueError: Collection hw-qdrant not found

In [85]:
from qdrant_client import QdrantClient

client = QdrantClient(":memory:")

In [86]:
from qdrant_client.models import VectorParams, Distance

client.create_collection(
    collection_name="hw-qdrant",
    vectors_config=VectorParams(size=512, distance=Distance.COSINE)
)

True

In [87]:
client.get_collections()

CollectionsResponse(collections=[CollectionDescription(name='hw-qdrant')])

In [88]:
from qdrant_client.models import PointStruct

points = []

for i, doc in enumerate(documents):
    points.append(
        PointStruct(
            id=i,
            vector=vectors[i].tolist(),
            payload=doc
        )
    )

client.upsert(
    collection_name="hw-qdrant",
    points=points
)

UpdateResult(operation_id=0, status=<UpdateStatus.COMPLETED: 'completed'>)

In [89]:
limit = 5

def qdrant_search(q):
    query_vector = embedding_model.encode(q["question"]).tolist()

    results = client.search(
        collection_name="hw-qdrant",
        query_vector=query_vector,
        limit=limit,
        query_filter={
            "must": [
                {
                    "key": "course",
                    "match": {"value": q["course"]}
                }
            ]
        }
    )

    return [hit.payload for hit in results]

In [90]:
evaluate(ground_truth, qdrant_search)

  0%|                                                                                         | 0/4627 [00:00<?, ?it/s]

AttributeError: 'QdrantClient' object has no attribute 'search'

In [91]:
pip install -U qdrant_client

Requirement already satisfied: qdrant_client in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (1.17.1)
Requirement already satisfied: grpcio>=1.41.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from qdrant_client) (1.80.0)
Requirement already satisfied: httpx>=0.20.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx[http2]>=0.20.0->qdrant_client) (0.28.1)
Requirement already satisfied: numpy>=2.1.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from qdrant_client) (2.3.2)
Requirement already satisfied: portalocker<4.0,>=2.7.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from qdrant_client) (3.2.0)
Requirement already satisfied: protobuf>=3.20.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from qdrant_client) (6.32.1)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from qdrant_client) (2.12.3)
Requirement already satisfied: urllib3<3,>=1.26.14 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from qdrant_client) (2.5.0)
Requirement already satisfied: pywin32>=226 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from portalocker<4.0,>=2.7.0->qdrant_client) (311)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from grpcio>=1.41.0->qdrant_client) (4.15.0)
Requirement already satisfied: anyio in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant_client) (4.11.0)
Requirement already satisfied: certifi in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant_client) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant_client) (1.0.9)
Requirement already satisfied: idna in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant_client) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpcore==1.*->httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant_client) (0.16.0)
Requirement already satisfied: h2<5,>=3 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from httpx[http2]>=0.20.0->qdrant_client) (4.3.0)
Requirement already satisfied: hyperframe<7,>=6.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from h2<5,>=3->httpx[http2]>=0.20.0->qdrant_client) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from h2<5,>=3->httpx[http2]>=0.20.0->qdrant_client) (4.1.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant_client) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant_client) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant_client) (0.4.2)
Requirement already satisfied: sniffio>=1.1 in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from anyio->httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant_client) (1.3.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [92]:
def qdrant_search(q):
    query_vector = embedding_model.encode(q["question"]).tolist()

    results = client.query_points(
        collection_name="hw-qdrant",
        query=query_vector,
        limit=limit,
        query_filter={
            "must": [
                {
                    "key": "course",
                    "match": {"value": q["course"]}
                }
            ]
        }
    )

    return [hit.payload for hit in results.points]

In [93]:
evaluate(ground_truth, qdrant_search)

  0%|                                                                                         | 0/4627 [00:00<?, ?it/s]

AttributeError: 'dict' object has no attribute 'must'

In [94]:
from qdrant_client.models import Filter, FieldCondition, MatchValue

def qdrant_search(q):
    query_vector = embedding_model.encode(q["question"]).tolist()

    results = client.query_points(
        collection_name="hw-qdrant",
        query=query_vector,
        limit=limit,
        query_filter=Filter(
            must=[
                FieldCondition(
                    key="course",
                    match=MatchValue(value=q["course"])
                )
            ]
        )
    )

    return [hit.payload for hit in results.points]

In [95]:
evaluate(ground_truth, qdrant_search)

100%|██████████████████████████████████████████████████████████████████████████████| 4627/4627 [02:16<00:00, 33.82it/s]

{'hit_rate': 0.2327642100713205, 'mrr': 0.15015128593040858}

In [96]:
from qdrant_client import QdrantClient, models

model_handle = "jinaai/jina-embeddings-v2-small-en"
collection_name = "hw-qdrant"
limit = 5

client = QdrantClient(":memory:")

In [97]:
client.create_collection(
    collection_name=collection_name,
    vectors_config=models.VectorParams(
        size=client.get_embedding_size(model_handle),
        distance=models.Distance.COSINE
    )
)

True

In [98]:
client.upload_collection(
    collection_name=collection_name,
    vectors=[
        models.Document(
            text=doc["question"] + " " + doc["text"],
            model=model_handle
        )
        for doc in documents
    ],
    payload=documents,
    ids=[doc["id"] for doc in documents]
)

ValueError: Point id c02e79ef is not a valid UUID

In [ ]:
def qdrant_search(q):
    results = client.query_points(
        collection_name=collection_name,
        query=models.Document(
            text=q["question"],
            model=model_handle
        ),
        query_filter=models.Filter(
            must=[
                models.FieldCondition(
                    key="course",
                    match=models.MatchValue(value=q["course"])
                )
            ]
        ),
        limit=limit
    )

    return [hit.payload for hit in results.points]

In [ ]:
evaluate(ground_truth, qdrant_search)

In [ ]:
from qdrant_client import QdrantClient, models

client = QdrantClient(":memory:")
collection_name = "hw-qdrant"
model_handle = "jinaai/jina-embeddings-v2-small-en"
limit = 5

In [100]:
client.create_collection(
    collection_name=collection_name,
    vectors_config=models.VectorParams(
        size=client.get_embedding_size(model_handle),
        distance=models.Distance.COSINE
    )
)

ValueError: Collection hw-qdrant already exists

In [ ]:
client.upload_collection(
    collection_name=collection_name,
    vectors=[
        models.Document(
            text=doc["question"] + " " + doc["text"],
            model=model_handle
        )
        for doc in documents
    ],
    payload=documents,
    ids=list(range(len(documents)))
)

In [ ]:
def qdrant_search(q):
    results = client.query_points(
        collection_name=collection_name,
        query=models.Document(
            text=q["question"],
            model=model_handle
        ),
        query_filter=models.Filter(
            must=[
                models.FieldCondition(
                    key="course",
                    match=models.MatchValue(value=q["course"])
                )
            ]
        ),
        limit=limit
    )

    return [hit.payload for hit in results.points]

In [ ]:
qdrant_search(ground_truth[0])

In [101]:
import time

start = time.time()
res = qdrant_search(ground_truth[0])
end = time.time()

print("Temps:", end - start)
print(res[:2])

Temps: 0.1929643154144287
[{'text': 'Yes, we will keep all the materials after the course finishes, so you can follow the course at your own pace after it finishes.\nYou can also continue looking at the homeworks and continue preparing for the next cohort. I guess you can also start working on your final capstone project.', 'section': 'General course-related questions', 'question': 'Course - Can I follow the course after it finishes?', 'course': 'data-engineering-zoomcamp', 'id': 'a482086d'}, {'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.", 'section': 'General course-related questions', 'question': 'Course - Can I still join the course after the start date?', 'course': 'data-engineering-zoomcamp', 'id': '7842b56a'}]

In [102]:
evaluate(ground_truth[:10], qdrant_search)

100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 24.34it/s]

{'hit_rate': 0.4, 'mrr': 0.175}

In [103]:
results_url = url_prefix + 'rag_evaluation/data/results-gpt4o-mini.csv'
df_results = pd.read_csv(results_url)
df_results.head()

,answer_llm,answer_orig,document,question,course
0,You can sign up for the course by visiting the...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Where can I sign up for the course?,machine-learning-zoomcamp
1,You can sign up using the link provided in the...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Can you provide a link to sign up?,machine-learning-zoomcamp
2,"Yes, there is an FAQ for the Machine Learning ...",Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Is there an FAQ for this Machine Learning course?,machine-learning-zoomcamp
3,The context does not provide any specific info...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Does this course have a GitHub repository for ...,machine-learning-zoomcamp
4,To structure your questions and answers for th...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,How can I structure my questions and answers f...,machine-learning-zoomcamp

In [104]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import make_pipeline

pipeline = make_pipeline(
    TfidfVectorizer(min_df=3),
    TruncatedSVD(n_components=128, random_state=1)
)

In [105]:
pipeline.fit(df_results.answer_llm + ' ' + df_results.answer_orig + ' ' + df_results.question)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer(min_df=3)),
                ('truncatedsvd',
                 TruncatedSVD(n_components=128, random_state=1))])

In [106]:
import numpy as np

def cosine(u, v):
    u_norm = np.sqrt(u.dot(u))
    v_norm = np.sqrt(v.dot(v))
    return u.dot(v) / (u_norm * v_norm)

In [107]:
scores = []

for _, row in df_results.iterrows():
    v_llm = pipeline.transform([row["answer_llm"]])[0]
    v_orig = pipeline.transform([row["answer_orig"]])[0]

    score = cosine(v_llm, v_orig)
    scores.append(score)

In [108]:
np.mean(scores)

np.float64(0.8415841233490402)

In [109]:
!pip install rouge

Collecting rouge
  Downloading rouge-1.0.1-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: six in c:\users\felix\appdata\local\programs\python\python313\lib\site-packages (from rouge) (1.17.0)
Downloading rouge-1.0.1-py3-none-any.whl (13 kB)
Installing collected packages: rouge
Successfully installed rouge-1.0.1

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [110]:
from rouge import Rouge

rouge_scorer = Rouge()

r = df_results.iloc[10]
scores = rouge_scorer.get_scores(r.answer_llm, r.answer_orig)[0]

scores

{'rouge-1': {'r': 0.45454545454545453,
  'p': 0.45454545454545453,
  'f': 0.45454544954545456},
 'rouge-2': {'r': 0.21621621621621623,
  'p': 0.21621621621621623,
  'f': 0.21621621121621637},
 'rouge-l': {'r': 0.3939393939393939,
  'p': 0.3939393939393939,
  'f': 0.393939388939394}}

In [111]:
from rouge import Rouge
import numpy as np

rouge_scorer = Rouge()

scores = []

for _, row in df_results.iterrows():
    score = rouge_scorer.get_scores(
        row.answer_llm,
        row.answer_orig
    )[0]['rouge-1']['f']

    scores.append(score)

np.mean(scores)

np.float64(0.3516946452113943)

In [112]:
import pandas as pd

url_prefix = 'https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main/03-evaluation/'
results_url = url_prefix + 'rag_evaluation/data/results-gpt4o.csv'

df_results = pd.read_csv(results_url)
df_results.head()

,answer_llm,answer_orig,document,question,course
0,The CONTEXT provided does not give specific in...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Where can I sign up for the course?,machine-learning-zoomcamp
1,You can sign up for the Machine Learning Zoomc...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Can you provide a link to sign up?,machine-learning-zoomcamp
2,"Yes, there is an FAQ for the Machine Learning ...",Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Is there an FAQ for this Machine Learning course?,machine-learning-zoomcamp
3,"No, the provided context does not include any ...",Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Does this course have a GitHub repository for ...,machine-learning-zoomcamp
4,To structure your questions and answers for th...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,How can I structure my questions and answers f...,machine-learning-zoomcamp

In [113]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import make_pipeline

pipeline = make_pipeline(
    TfidfVectorizer(min_df=3),
    TruncatedSVD(n_components=128, random_state=1)
)

In [114]:
pipeline.fit(
    df_results.answer_llm + ' ' +
    df_results.answer_orig + ' ' +
    df_results.question
)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer(min_df=3)),
                ('truncatedsvd',
                 TruncatedSVD(n_components=128, random_state=1))])

In [115]:
import numpy as np

def cosine(u, v):
    u_norm = np.sqrt(u.dot(u))
    v_norm = np.sqrt(v.dot(v))
    return u.dot(v) / (u_norm * v_norm)

In [116]:
row = df_results.iloc[0]

v_llm = pipeline.transform([row.answer_llm])[0]
v_orig = pipeline.transform([row.answer_orig])[0]

cosine(v_llm, v_orig)

np.float64(0.655950000464725)

In [117]:
scores = []

for _, row in df_results.iterrows():
    v_llm = pipeline.transform([row.answer_llm])[0]
    v_orig = pipeline.transform([row.answer_orig])[0]

    score = cosine(v_llm, v_orig)
    scores.append(score)

In [118]:
np.mean()

TypeError: mean() missing 1 required positional argument: 'a'

In [119]:
np.mean(scores)

np.float64(0.8490920587383466)

In [120]:
results_url = url_prefix + 'rag_evaluation/data/results-gpt35.csv'
df_results = pd.read_csv(results_url)
df_results.head()

,answer_llm,answer_orig,document,question,course
0,You can sign up for the course by going to the...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Where can I sign up for the course?,machine-learning-zoomcamp
1,"I am sorry, but there is no direct link provid...",Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Can you provide a link to sign up?,machine-learning-zoomcamp
2,"Yes, there is an FAQ for the Machine Learning ...",Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Is there an FAQ for this Machine Learning course?,machine-learning-zoomcamp
3,"No, the course does not have a GitHub reposito...",Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Does this course have a GitHub repository for ...,machine-learning-zoomcamp
4,Based on the information provided in the FAQ d...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,How can I structure my questions and answers f...,machine-learning-zoomcamp

In [121]:
results-gpt35.csv

NameError: name 'gpt35' is not defined

In [122]:
results_url = url_prefix + 'rag_evaluation/data/results-gpt35.csv'
df_results = pd.read_csv(results_url)
df_results.head()

,answer_llm,answer_orig,document,question,course
0,You can sign up for the course by going to the...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Where can I sign up for the course?,machine-learning-zoomcamp
1,"I am sorry, but there is no direct link provid...",Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Can you provide a link to sign up?,machine-learning-zoomcamp
2,"Yes, there is an FAQ for the Machine Learning ...",Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Is there an FAQ for this Machine Learning course?,machine-learning-zoomcamp
3,"No, the course does not have a GitHub reposito...",Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Does this course have a GitHub repository for ...,machine-learning-zoomcamp
4,Based on the information provided in the FAQ d...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,How can I structure my questions and answers f...,machine-learning-zoomcamp

In [123]:
pipeline.fit(
    df_results.answer_llm + ' ' +
    df_results.answer_orig + ' ' +
    df_results.question
)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer(min_df=3)),
                ('truncatedsvd',
                 TruncatedSVD(n_components=128, random_state=1))])

In [124]:
scores = []

for _, row in df_results.iterrows():
    v_llm = pipeline.transform([row.answer_llm])[0]
    v_orig = pipeline.transform([row.answer_orig])[0]

    score = cosine(v_llm, v_orig)
    scores.append(score)

In [125]:
np.mean(scores)

np.float64(0.8161876769486024)

In [126]:
results_url = url_prefix + 'rag_evaluation/data/results-gpt4o-mini.csv'
df_results = pd.read_csv(results_url)

df_results.head()

,answer_llm,answer_orig,document,question,course
0,You can sign up for the course by visiting the...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Where can I sign up for the course?,machine-learning-zoomcamp
1,You can sign up using the link provided in the...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Can you provide a link to sign up?,machine-learning-zoomcamp
2,"Yes, there is an FAQ for the Machine Learning ...",Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Is there an FAQ for this Machine Learning course?,machine-learning-zoomcamp
3,The context does not provide any specific info...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,Does this course have a GitHub repository for ...,machine-learning-zoomcamp
4,To structure your questions and answers for th...,Machine Learning Zoomcamp FAQ\nThe purpose of ...,0227b872,How can I structure my questions and answers f...,machine-learning-zoomcamp

In [127]:
pipeline.fit(
    df_results.answer_llm + ' ' +
    df_results.answer_orig + ' ' +
    df_results.question
)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer(min_df=3)),
                ('truncatedsvd',
                 TruncatedSVD(n_components=128, random_state=1))])

In [128]:
scores = []

for _, row in df_results.iterrows():
    v_llm = pipeline.transform([row.answer_llm])[0]
    v_orig = pipeline.transform([row.answer_orig])[0]

    score = cosine(v_llm, v_orig)
    scores.append(score)

In [129]:
np.mean(scores)

np.float64(0.8415841233490402)

In [130]:
model = "gpt-4o-mini"

In [131]:
prompt = prompt_template.format(
    question=question,
    original_answer=original_answer,
    generated_answer=generated_answer
)

NameError: name 'original_answer' is not defined

In [132]:
df_sample = df.sample(n=100, random_state=1)

NameError: name 'df' is not defined

In [133]:
df_sample = df.sample(n=100, random_state=1)

NameError: name 'df' is not defined

In [134]:
%whos

Variable                      Type                   Data/Info
--------------------------------------------------------------
Distance                      EnumType               <enum 'Distance'>
FieldCondition                ModelMetaclass         <class 'qdrant_client.htt<...>s.models.FieldCondition'>
Filter                        ModelMetaclass         <class 'qdrant_client.http.models.models.Filter'>
MatchValue                    ModelMetaclass         <class 'qdrant_client.htt<...>odels.models.MatchValue'>
OpenAI                        type                   <class 'openai.OpenAI'>
PointStruct                   ModelMetaclass         <class 'qdrant_client.htt<...>dels.models.PointStruct'>
QdrantClient                  type                   <class 'qdrant_client.qdr<...>ant_client.QdrantClient'>
Rouge                         type                   <class 'rouge.rouge.Rouge'>
SentenceTransformer           type                   <class 'sentence_transfor<...>mer.SentenceTransformer'>
TfidfVectorizer               type                   <class 'sklearn.feature_e<...>on.text.TfidfVectorizer'>
TruncatedSVD                  type                   <class 'sklearn.decomposi<...>ncated_svd.TruncatedSVD'>
VectorParams                  ModelMetaclass         <class 'qdrant_client.htt<...>els.models.VectorParams'>
VectorSearch                  type                   <class 'minsearch.vector.VectorSearch'>
X                             ndarray                948x128: 121344 elems, type `float64`, 970752 bytes (948.0 kb)
client                        QdrantClient           <qdrant_client.qdrant_cli<...>ct at 0x0000020DB9A18C30>
collection_name               str                    hw-qdrant
cosine                        function               <function cosine at 0x0000020F93D18680>
course                        str                    machine-learning-zoomcamp
df_ground_truth               DataFrame              Shape: (4627, 3)
df_results                    DataFrame              Shape: (1830, 5)
doc                           dict                   n=5
doc_id                        str                    c622de13
doc_index                     dict                   n=375
docs_url                      str                    https://raw.githubusercon<...>n/documents-with-ids.json
documents                     list                   n=948
embedding_model               SentenceTransformer    SentenceTransformer(\n  (<...>nclude_prompt': True})\n)
end                           float                  1775081780.335397
evaluate                      function               <function evaluate at 0x0000020DB079F100>
expected_doc_id               str                    c622de13
f_in                          BufferedReader         <_io.BufferedReader name='results.pkl'>
f_out                         BufferedWriter         <_io.BufferedWriter name='results.pkl'>
final_results                 list                   n=145
generate_questions            function               <function generate_questi<...>ns at 0x0000020DE50FB560>
ground_truth                  list                   n=4627
ground_truth_url              str                    https://raw.githubusercon<...>ion/ground-truth-data.csv
hit_rate                      function               <function hit_rate at 0x0000020DB0CBFE20>
i                             int                    947
index                         Index                  <minsearch.minsearch.Inde<...>ct at 0x0000020DB08BDD10>
json                          module                 <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
limit                         int                    5
make_pipeline                 function               <function make_pipeline at 0x0000020DB0EDECA0>
minsearch                     module                 <module 'minsearch' from <...>\minsearch\\__init__.py'>
minsearch_search              function               <function minsearch_search at 0x0000020DB09D0680>
model                         str                    gpt-4o-mini
model_handle                  str                    jinaai/jina-embeddings-v2-small-en
models                        module                 <module 'qdrant_client.mo<...>nt\\models\\__init__.py'>
mrr                           function               <function mrr at 0x0000020DB079FEC0>
np                            module                 <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os                            module                 <module 'os' (frozen)>
parsed                        dict                   n=1
pd                            module                 <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
pickle                        module                 <module 'pickle' from 'C:<...>thon313\\Lib\\pickle.py'>
pipeline                      Pipeline               Pipeline(steps=[('tfidfve<...>s=128, random_state=1))])
points                        list                   n=948
prompt                        str                    You emulate a student who<...>ithout using code blocks.
prompt_template               str                    You emulate a student who<...>ithout using code blocks.
q                             dict                   n=3
qdrant_search                 function               <function qdrant_search at 0x0000020DD730B380>
query                         str                    In what situations should<...>matrices to avoid errors?
question                      str                    In what situations should<...>matrices to avoid errors?
question_text_vector_search   function               <function question_text_v<...>ch at 0x0000020DB0F0C540>
question_vector_search        function               <function question_vector<...>ch at 0x0000020DB0F0C4A0>
questions                     list                   n=5
r                             Series                 Shape: (5,)
relevance                     list                   n=5
relevance_total               list                   n=145
requests                      module                 <module 'requests' from '<...>\\requests\\__init__.py'>
res                           list                   n=5
response                      ChatCompletion         ChatCompletion(id='chatcm<...>ens=0, cached_tokens=0)))
response_text                 str                    {\n  "questions": [\n    <...>g course?"\n    }\n  ]\n}
results                       list                   n=5
results_url                   str                    https://raw.githubusercon<...>ta/results-gpt4o-mini.csv
rouge_scorer                  Rouge                  <rouge.rouge.Rouge object at 0x0000020F93AC8190>
row                           Series                 Shape: (5,)
score                         float64                0.7709346898789302
scores                        list                   n=1830
search                        function               <function search at 0x0000020D8C2A0180>
start                         float                  1775081780.1424327
sys                           module                 <module 'sys' (built-in)>
t                             str                    How to destroy infrastruc<...>\nAdded by Erick Calderin
text                          str                    How to destroy infrastruc<...>\nAdded by Erick Calderin
texts                         list                   n=948
time                          module                 <module 'time' (built-in)>
tqdm                          type                   <class 'tqdm.asyncio.tqdm_asyncio'>
url_prefix                    str                    https://raw.githubusercon<...>mcamp/main/03-evaluation/
v_llm                         ndarray                128: 128 elems, type `float64`, 1024 bytes
v_orig                        ndarray                128: 128 elems, type `float64`, 1024 bytes
vec                           ndarray                512: 512 elems, type `float32`, 2048 bytes
vectors                       ndarray                948x512: 485376 elems, type `float32`, 1941504 bytes (1.8515625 Mb)
vindex                        VectorSearch           <minsearch.vector.VectorS<...>ct at 0x0000020DB0D54B90>

In [135]:
df_sample = df_results.sample(n=100, random_state=1)

In [136]:
sample = df_sample.to_dict(orient="records")

In [137]:
for record in sample:
    print(record)

{'answer_llm': 'The syntax for using `precision_recall_fscore_support` in Python is as follows:\n\n```python\nfrom sklearn.metrics import precision_recall_fscore_support\nprecision, recall, fscore, support = precision_recall_fscore_support(y_val, y_val_pred, zero_division=0)\n```', 'answer_orig': 'Scikit-learn offers another way: precision_recall_fscore_support\nExample:\nfrom sklearn.metrics import precision_recall_fscore_support\nprecision, recall, fscore, support = precision_recall_fscore_support(y_val, y_val_pred, zero_division=0)\n(Gopakumar Gopinathan)', 'document': '403bbdd8', 'question': 'What is the syntax for using precision_recall_fscore_support in Python?', 'course': 'machine-learning-zoomcamp'}
{'answer_llm': 'To avoid pickle errors when using waitress, you should modify your scripts by placing the custom column transformer class into a separate module. Then, import this module in both the script that saves the model (e.g., train.py) and the script that loads the model (e.g., predict.py). This way, when you use pickle, it will look for the class in the module rather than in the __main__ namespace, thus preventing the pickle error.', 'answer_orig': "When running a docker container with waitress serving the app.py for making predictions, pickle will throw an error that can't get attribute <name_of_class> on module __main__.\nThis does not happen when Flask is used directly, i.e. not through waitress.\nThe problem is that the model uses a custom column transformer class, and when the model was saved, it was saved from the __main__ module (e.g. python train.py). Pickle will reference the class in the global namespace (top-level code): __main__.<custom_class>.\nWhen using waitress, waitress will load the predict_app module and this will call pickle.load, that will try to find __main__.<custom_class> that does not exist.\nSolution:\nPut the class into a separate module and import it in both the script that saves the model (e.g. train.py) and the script that loads the model (e.g. predict.py)\nNote: If Flask is used (no waitress) in predict.py, and predict.py has the definition of the class, When  it is run: python predict.py, it will work because the class is in the same namespace as the one used when the model was saved (__main__).\nDetailed info: https://stackoverflow.com/questions/27732354/unable-to-load-files-using-pickle-and-multiple-modules\nMarcos MJD", 'document': '236864c2', 'question': 'How should I modify my scripts to avoid pickle errors when using waitress?', 'course': 'machine-learning-zoomcamp'}
{'answer_llm': 'The command to launch a container image in interactive mode is:\n\n```\ndocker run -it --entrypoint bash <image>\n```', 'answer_orig': 'Launch the container image in interactive mode and overriding the entrypoint, so that it starts a bash command.\ndocker run -it --entrypoint bash <image>\nIf the container is already running, execute a command in the specific container:\ndocker ps (find the container-id)\ndocker exec -it <container-id> bash\n(Marcos MJD)', 'document': '63a81b57', 'question': 'What command launches a container image in interactive mode?', 'course': 'machine-learning-zoomcamp'}
{'answer_llm': 'Yes, you can make a pull request for homework solutions using PyTorch. Although the lessons and homework primarily use Keras, you are encouraged to submit equivalent solutions in PyTorch.', 'answer_orig': 'Pytorch is also a deep learning framework that allows to do equivalent tasks as keras. Here is a tutorial to create a CNN from scratch using pytorch :\nhttps://blog.paperspace.com/writing-cnns-from-scratch-in-pytorch/\nThe functions have similar goals. The syntax can be slightly different. For the lessons and the homework, we use keras, but one can feel free to make a pull request with the equivalent with pytorch for lessons and homework!\nMélanie Fouesnard', 'document': 'c4ff26e5', 'question': 'Can we make a pull request for homework solutions using Pytorch?', 'course': 'machine-learning-zoomcamp'}
{'answer_llm': "The cause of the pip version error in this week's serverless deep learning section could be a version conflict in Scikit-Learn. Specifically, if you are using a different version than what was used during the model training, it can lead to warnings and potential breaking code or invalid results. To resolve this, make sure to use the same version of Scikit-Learn that was used for training the model. For instance, if you trained with version 1.1.1, you should use that same version in your virtual environment.", 'answer_orig': 'When running docker build -t dino-dragon-model it returns the above error\nThe most common source of this error in this week is because Alex video shows a version of the wheel with python 8, we need to find a wheel with the version that we are working on. In this case python 9. Another common error is to copy the link, this will also produce the same error, we need to download the raw format:\nhttps://github.com/alexeygrigorev/tflite-aws-lambda/raw/main/tflite/tflite_runtime-2.7.0-cp39-cp39-linux_x86_64.whl\nPastor Soto', 'document': '42c09143', 'question': "What might be the cause of the pip version error in this week's serverless deep learning section?", 'course': 'machine-learning-zoomcamp'}
{'answer_llm': 'After editing the metrics-server, you should run the command: \n\n>>kubectl get hpa', 'answer_orig': 'In case the HPA instance does not run correctly even after installing the latest version of Metrics Server from the components.yaml manifest with:\n>>kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml\nAnd the targets still appear as <unknown>\nRun >>kubectl edit deploy -n kube-system metrics-server\nAnd search for this line:\nargs:\n- --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname\nAdd this line in the middle:  - --kubelet-insecure-tls\nSo that it stays like this:\nargs:\n- --kubelet-insecure-tls\n- --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname\nSave and run again >>kubectl get hpa\nAdded by Marilina Orihuela', 'document': 'df023a13', 'question': 'What command do we run after editing the metrics-server to check the HPA status again?', 'course': 'machine-learning-zoomcamp'}
{'answer_llm': 'To check your AWS CLI version for eksctl compatibility, you should ensure that you are using AWS CLI version 2. You can verify your version by running the command:\n\n```\naws --version\n```\n\nFor more information, you can refer to the AWS CLI v2 migration instructions found at the following link: https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-instructions.html.', 'answer_orig': 'Make sure you are on AWS CLI v2 (check with aws --version)\nhttps://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-instructions.html', 'document': '00882c83', 'question': 'How can I check my AWS CLI version for eksctl compatibility?', 'course': 'machine-learning-zoomcamp'}
{'answer_llm': 'One main reason for different accuracy values is the way of splitting data. Different methods of splitting the dataset can result in variations in the data used for training, validation, and testing, even if the ratios remain the same. For example, using different random states in the train-test split can lead to different samples being included in the train and test sets, which affects accuracy measurements.', 'answer_orig': 'One main reason behind that, is the way of splitting data. For example, we want to split data into train/validation/test with the ratios 60%/20%/20% respectively.\nAlthough the following two options end up with the same ratio, the data itself is a bit different and not 100% matching in each case.\n1)\ndf_train, df_temp = train_test_split(df, test_size=0.4, random_state=42)\ndf_val, df_test = train_test_split(df_temp, test_size=0.5, random_state=42)\n2)\ndf_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)\ndf_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)\nTherefore, I would recommend using the second method which is more consistent with the lessons and thus the homeworks.\nIbraheem Taha', 'document': '25481ce5', 'question': 'What is one main reason for different accuracy values?', 'course': 'machine-learning-zoomcamp'}
{'answer_llm': "If you lose the REMOTE_URI variable after the session ends, you will need to set it again by exporting it in your terminal. You can do this by using the command `export REMOTE_URI=your_URI_address`, where you should replace `your_URI_address` with your actual URI. Note that you will lose this variable once the session is terminated, so you'll need to do this each time you start a new session.", 'answer_orig': 'Solution description\nIn the unit 9.6, Alexey ran the command echo ${REMOTE_URI} which turned the URI address in the terminal. There workaround is to set a local variable (REMOTE_URI) and assign your URI address in the terminal and use it to login the registry, for instance, REMOTE_URI=2278222782.dkr.ecr.ap-south-1.amazonaws.com/clothing-tflite-images (fake address). One caveat is that you will lose this variable once the session is terminated.\nI also had the same problem on Ubuntu terminal. I executed the following two commands:\n$ export REMOTE_URI=1111111111.dkr.ecr.us-west-1.amazonaws.com/clothing-tflite-images:clothing-model-xception-v4-001\n$ echo $REMOTE_URI\n111111111.dkr.ecr.us-west-1.amazonaws.com/clothing-tflite-images:clothing-model-xception-v4-001\nNote: 1. no curly brackets (e.g. echo ${REMOTE_URI}) needed unlike in video 9.6,\n2. Replace REMOTE_URI with your URI\n(Bhaskar Sarma)', 'document': '60fa95ed', 'question': 'What should I do if I lose the REMOTE_URI variable after the session ends?', 'course': 'machine-learning-zoomcamp'}
{'answer_llm': 'You can find the script for generating the Kitchenware Classification Competition dataset at the following link: kitchenware-dataset-generator | Kaggle.', 'answer_orig': 'The image dataset for the competition was in a different layout from what we used in the dino vs dragon lesson. Since that’s what was covered, some folks were more comfortable with that setup, so I wrote a script that would generate it for them\nIt can be found here: kitchenware-dataset-generator | Kaggle\nMartin Uribe', 'document': '20174c95', 'question': 'Where can I find the script for generating the Kitchenware Classification Competition dataset?', 'course': 'machine-learning-zoomcamp'}
{'answer_llm': 'The solution for the TensorFlow Serving error on Apple M1 Mac is to use a different Docker image. Instead of using `tensorflow/serving:2.7.0`, you should run the following commands:\n\n1. Pull the latest ARM64-compatible image:\n   ```bash\n   docker pull emacski/tensorflow-serving:latest\n   ```\n\n2. Run the Docker container using the pulled image:\n   ```bash\n   docker run -it --rm \\\n   -p 8500:8500 \\\n   -v $(pwd)/clothing-model:/models/clothing-model/1 \\\n   -e MODEL_NAME="clothing-model" \\\n   emacski/tensorflow-serving:latest-linux_arm64\n   ```\n\nFor more details, you can visit [this GitHub repository](https://github.com/emacski/tensorflow-serving-arm).', 'answer_orig': 'While trying to run the docker code on M1:\ndocker run --platform linux/amd64 -it --rm \\\n-p 8500:8500 \\\n-v $(pwd)/clothing-model:/models/clothing-model/1 \\\n-e MODEL_NAME="clothing-model" \\\ntensorflow/serving:2.7.0\nIt outputs the error:\nError:\nStatus: Downloaded newer image for tensorflow/serving:2.7.0\n[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2345] CHECK failed: file != nullptr:\nterminate called after throwing an instance of \'google::protobuf::FatalException\'\nwhat():  CHECK failed: file != nullptr:\nqemu: uncaught target signal 6 (Aborted) - core dumped\n/usr/bin/tf_serving_entrypoint.sh: line 3:     8 Aborted                 tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"\nSolution\ndocker pull emacski/tensorflow-serving:latest\ndocker run -it --rm \\\n-p 8500:8500 \\\n-v $(pwd)/clothing-model:/models/clothing-model/1 \\\n-e MODEL_NAME="clothing-model" \\\nemacski/tensorflow-serving:latest-linux_arm64\nSee more here: https://github.com/emacski/tensorflow-serving-arm\nAdded by Daniel Egbo', 'document': '5bda3b94', 'question': 'What is the solution for the TensorFlow Serving error on Apple M1 Mac?', 'course': 'machine-learning-zoomcamp'}
{'answer_llm': 'To resolve the NotSupportedError in section 5, you can take the following steps:\n\n1. **Downgrade the protobuf package**: The recommended version is 3.20.1. You can do this by running the following command:\n   ```bash\n   pipenv install protobuf==3.20.1\n   ```\n\n2. **Regenerate your Protobuf files**: If you have access to the source files and can regenerate them, ensure that you use `protoc` version 3.19.0 or higher.\n\n3. **Alternative workaround**: If you cannot regenerate your protos, you can either downgrade the protobuf package to version 3.20.x or lower, or set the environment variable:\n   ```bash\n   export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python\n   ```\n   Note that the latter will use a slower pure-Python parser.\n\nMake sure to follow these steps to address the issue effectively.', 'answer_orig': 'Question:\nWhen executing\neb local run  --port 9696\nI get the following error:\nERROR: NotSupportedError - You can use "eb local" only with preconfigured, generic and multicontainer Docker platforms.\nAnswer:\nThere are two options to fix this:\nRe-initialize by running eb init -i and choosing the options from a list (the first default option for docker platform should be fine).\nEdit the ‘.elasticbeanstalk/config.yml’ directly changing the default_platform from Docker to default_platform: Docker running on 64bit Amazon Linux 2023\nThe disadvantage of the second approach is that the option might not be available the following years\nAdded by Alex Litvinov', 'document': 'd04e77f8', 'question': 'What steps can I take to resolve the NotSupportedError in section 5?', 'course': 'machine-learning-zoomcamp'}
{'answer_llm': "The solution for fixing the 'Failed to find data adapter' error in the Keras model training was added by Tzvi Friedman.", 'answer_orig': "While training a Keras model you get the error “Failed to find data adapter that can handle input: <class 'keras.src.preprocessing.image.ImageDataGenerator'>, <class 'NoneType'>” you may have unintentionally passed the image generator instead of the dataset to the model\ntrain_gen = ImageDataGenerator(rescale=1./255)\ntrain_ds = train_gen.flow_from_directory(…)\nhistory_after_augmentation = model.fit(\ntrain_gen, # this should be train_ds!!!\nepochs=10,\nvalidation_data=test_gen # this should be test_ds!!!\n)\nThe fix is simple and probably obvious once pointed out, use the training and validation dataset (train_ds and val_ds) returned from flow_from_directory\nAdded by Tzvi Friedman", 'document': '62722d72', 'question': "Who added the solution for fixing the 'Failed to find data adapter' error in the Keras model training?", 'course': 'machine-learning-zoomcamp'}
{'answer_llm': "The first step to install kind through choco is to launch a PowerShell terminal with administrator privilege and then install the choco library using the following command:\n\n```\nSet-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))\n```", 'answer_orig': "First you need to launch a powershell terminal with administrator privilege.\nFor this we need to install choco library first through the following syntax in powershell:\nSet-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))\nKrishna Anand", 'document': '03b5fc59', 'question': "What's the first step to install kind through choco?", 'course': 'machine-learning-zoomcamp'}
{'answer_llm': 'You can fetch data for homework using the `requests` library with the following method:\n\n```python\nimport requests\n\n# Get data for homework\nurl = \'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv\'\nresponse = requests.get(url)\n\nif response.status_code == 200:\n    with open(\'housing.csv\', \'wb\') as file:\n        file.write(response.content)\nelse:\n    print("Download failed.")\n```\n\nThis code retrieves the dataset from GitHub and saves it as \'housing.csv\' on your local machine.', 'answer_orig': 'Above users showed how to load the dataset directly from github. Here is another useful way of doing this using the `requests` library:\n# Get data for homework\nimport requests\nurl = \'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv\'\nresponse = requests.get(url)\nif response.status_code == 200:\nwith open(\'housing.csv\', \'wb\') as file:\nfile.write(response.content)\nelse:\nprint("Download failed.")\nTyler Simpson', 'document': '8d209d6d', 'question': 'Could you share a method to fetch data for homework using the requests library?', 'course': 'machine-learning-zoomcamp'}
{'answer_llm': 'Yes, you can use the `mean_squared_error` function from `sklearn.metrics` to compute RMSE in one step by setting the `squared` parameter to `False`. This allows you to get the RMSE directly without needing to take the square root afterwards. Here’s how you can do it:\n\n```python\nfrom sklearn.metrics import mean_squared_error\nrms = mean_squared_error(y_actual, y_predicted, squared=False)\n```', 'answer_orig': 'Instead of using np.sqrt() as the second step. You can extract it using like this way :\nmean_squared_error(y_val, y_predict_val,squared=False)\nAhmed Okka', 'document': 'a7e7cdd2', 'question': 'Can I use mean_squared_error to compute RMSE in one step?', 'course': 'machine-learning-zoomcamp'}
{'answer_llm': 'You can find documentation on how Lambda functions are initialized at the following links:\n\n1. [Creating Lambda container images](https://docs.aws.amazon.com/lambda/latest/dg/images-create.html)\n2. [Lambda runtimes API documentation](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html)', 'answer_orig': 'I wanted to understand how lambda container images work in depth and how lambda functions are initialized, for this reason, I found the following documentation\nhttps://docs.aws.amazon.com/lambda/latest/dg/images-create.html\nhttps://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html\nAdded by Alejandro aponte', 'document': '4d98cd09', 'question': 'Where can I find documentation on how Lambda functions are initialized?', 'course': 'machine-learning-zoomcamp'}
{'answer_llm': 'To read data from a GitHub URL using pandas, you can use the following code:\n\n```python\ndf = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv")\n```\n\nThis will directly load the dataset into a pandas dataframe from the provided GitHub link.', 'answer_orig': 'The dataset can be read directly to pandas dataframe from the github link using the technique shown below\ndfh=pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv")\nKrishna Anand', 'document': '0b3eaf92', 'question': 'Could you explain how to read data from a GitHub URL using pandas?', 'course': 'machine-learning-zoomcamp'}

In [138]:
sample[0]

{'answer_llm': 'The syntax for using `precision_recall_fscore_support` in Python is as follows:\n\n```python\nfrom sklearn.metrics import precision_recall_fscore_support\nprecision, recall, fscore, support = precision_recall_fscore_support(y_val, y_val_pred, zero_division=0)\n```',
 'answer_orig': 'Scikit-learn offers another way: precision_recall_fscore_support\nExample:\nfrom sklearn.metrics import precision_recall_fscore_support\nprecision, recall, fscore, support = precision_recall_fscore_support(y_val, y_val_pred, zero_division=0)\n(Gopakumar Gopinathan)',
 'document': '403bbdd8',
 'question': 'What is the syntax for using precision_recall_fscore_support in Python?',
 'course': 'machine-learning-zoomcamp'}

In [139]:
prompt_template = """
You are an expert evaluator.

You are given:

Question: {question}

Original Answer: {answer_orig}

Generated Answer: {answer_llm}

Your task is to evaluate whether the generated answer is relevant and correct.

Return your answer in parsable JSON format without using code blocks:

{
    "relevance": "relevant | partly relevant | non relevant",
    "explanation": "short explanation"
}
""".strip()

In [140]:
record = sample[0]

prompt = prompt_template.format(
    question=record['question'],
    answer_orig=record['answer_orig'],
    answer_llm=record['answer_llm']
)

print(prompt)

KeyError: '\n    "relevance"'

In [141]:
prompt_template = """
You are an expert evaluator.

You are given:

Question: {question}

Original Answer: {answer_orig}

Generated Answer: {answer_llm}

Your task is to evaluate whether the generated answer is relevant and correct.

Return your answer in parsable JSON format without using code blocks:

{{
    "relevance": "relevant | partly relevant | non relevant",
    "explanation": "short explanation"
}}
""".strip()

In [142]:
record = sample[0]

prompt = prompt_template.format(
    question=record['question'],
    answer_orig=record['answer_orig'],
    answer_llm=record['answer_llm']
)

print(prompt)

You are an expert evaluator.

You are given:

Question: What is the syntax for using precision_recall_fscore_support in Python?

Original Answer: Scikit-learn offers another way: precision_recall_fscore_support
Example:
from sklearn.metrics import precision_recall_fscore_support
precision, recall, fscore, support = precision_recall_fscore_support(y_val, y_val_pred, zero_division=0)
(Gopakumar Gopinathan)

Generated Answer: The syntax for using `precision_recall_fscore_support` in Python is as follows:

```python
from sklearn.metrics import precision_recall_fscore_support
precision, recall, fscore, support = precision_recall_fscore_support(y_val, y_val_pred, zero_division=0)
```

Your task is to evaluate whether the generated answer is relevant and correct.

Return your answer in parsable JSON format without using code blocks:

{
    "relevance": "relevant | partly relevant | non relevant",
    "explanation": "short explanation"
}

In [143]:
answer = llm(prompt, model="gpt-4o-mini")
print(answer)

NameError: name 'llm' is not defined

In [144]:
def llm(prompt, model="gpt-4o-mini"):
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message.content

In [145]:
answer = llm(prompt, model="gpt-4o-mini")
print(answer)

AttributeError: 'QdrantClient' object has no attribute 'chat'

In [146]:
openai_client = OpenAI()

In [147]:
def llm(prompt, model="gpt-4o-mini"):
    response = openai_client.chat.completions.create(
        model=model,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message.content

In [148]:
answer = llm(prompt, model="gpt-4o-mini")
print(answer)

{
    "relevance": "relevant",
    "explanation": "The generated answer correctly provides the syntax for using the `precision_recall_fscore_support` function in Python, along with a proper import statement and example usage."
}

In [149]:
parsed = json.loads(answer)
parsed

{'relevance': 'relevant',
 'explanation': 'The generated answer correctly provides the syntax for using the `precision_recall_fscore_support` function in Python, along with a proper import statement and example usage.'}

In [150]:
parsed['relevance']

'relevant'

In [151]:
parsed['explanation']

'The generated answer correctly provides the syntax for using the `precision_recall_fscore_support` function in Python, along with a proper import statement and example usage.'

In [152]:
answers = []

for record in sample[:5]:
    prompt = prompt_template.format(
        question=record['question'],
        answer_orig=record['answer_orig'],
        answer_llm=record['answer_llm']
    )
    
    answer = llm(prompt)
    parsed = json.loads(answer)
    
    answers.append(parsed)

answers

[{'relevance': 'relevant',
  'explanation': 'The generated answer correctly provides the syntax for using precision_recall_fscore_support, including the appropriate import statement and parameters, thereby addressing the original question accurately.'},
 {'relevance': 'relevant',
  'explanation': "The generated answer accurately summarizes the necessary changes to avoid pickle errors when using waitress, specifically by moving the custom class to a separate module and importing it where needed. It aligns with the original answer's explanation and provides a clear solution."},
 {'relevance': 'relevant',
  'explanation': "The generated answer accurately provides the command to launch a container image in interactive mode, matching the original answer's content regarding the use of 'docker run -it --entrypoint bash <image>'."},
 {'relevance': 'relevant',
  'explanation': "The generated answer accurately addresses the question by confirming that a pull request can be made for homework solutions using PyTorch, in line with the original answer's encouragement to submit equivalent solutions."},
 {'relevance': 'non relevant',
  'explanation': 'The generated answer addresses a different issue related to Scikit-Learn version conflicts, whereas the original question specifically pertains to a pip version error related to a wheel for Python. The focus and context are not aligned.'}]

In [153]:
for record in sample[:5]:

_IncompleteInputError: incomplete input (2498449979.py, line 1)

In [154]:
answers = []

for record in sample:
    prompt = prompt_template.format(
        question=record['question'],
        answer_orig=record['answer_orig'],
        answer_llm=record['answer_llm']
    )
    
    answer = llm(prompt)
    parsed = json.loads(answer)
    
    answers.append(parsed)

In [155]:
answers = []

for record in sample:
    prompt = prompt_template.format(
        question=record['question'],
        answer_orig=record['answer_orig'],
        answer_llm=record['answer_llm']
    )

    answer = llm(prompt)
    parsed = json.loads(answer)

    answers.append(parsed)

In [156]:
answers = []

for i, record in enumerate(sample[:3]):
    print(f"Traitement record {i+1}/3")

    prompt = prompt_template.format(
        question=record['question'],
        answer_orig=record['answer_orig'],
        answer_llm=record['answer_llm']
    )

    answer = llm(prompt)
    parsed = json.loads(answer)

    answers.append(parsed)

print("Terminé")
answers

Traitement record 1/3
Traitement record 2/3
Traitement record 3/3
Terminé

[{'relevance': 'relevant',
  'explanation': 'The generated answer directly provides the required syntax for using `precision_recall_fscore_support`, which matches the original question.'},
 {'relevance': 'relevant',
  'explanation': 'The generated answer correctly captures the essential solution to the problem of pickle errors when using waitress by advising the user to move the custom class to a separate module and import it in both scripts. This addresses the namespace issue outlined in the original question and maintains the context of the discussion.'},
 {'relevance': 'relevant',
  'explanation': 'The generated answer correctly identifies the command to launch a container image in interactive mode, including the use of the --entrypoint option to start a bash command, which aligns with the original answer.'}]

In [157]:
print("test")

test

In [158]:
mini_prompt = "Say only: ok"

answer = llm(mini_prompt, model="gpt-4o-mini")
print(answer)

ok

In [159]:
answers = []

for i, record in enumerate(sample[:3]):
    prompt = prompt_template.format(
        question=record['question'],
        answer_orig=record['answer_orig'],
        answer_llm=record['answer_llm']
    )

    answer = llm(prompt, model="gpt-4o-mini")
    parsed = json.loads(answer)
    answers.append(parsed)

    print(f"Record {i+1}/3 terminé")
    print(parsed)
    print("-----")

Record 1/3 terminé
{'relevance': 'relevant', 'explanation': "The generated answer accurately provides the syntax for using the precision_recall_fscore_support function in Python, matching the original answer's content and format."}
-----
Record 2/3 terminé
{'relevance': 'relevant', 'explanation': "The generated answer correctly summarizes the original answer's key points regarding the issue with pickle errors when using waitress and provides the appropriate solution of separating the class into its own module, which aligns with the original explanation."}
-----
Record 3/3 terminé
{'relevance': 'relevant', 'explanation': 'The generated answer accurately provides the command to launch a container image in interactive mode, matching the information given in the original answer.'}
-----

In [161]:
answers = []

for i, record in enumerate(sample):
    prompt = prompt_template.format(
        question=record['question'],
        answer_orig=record['answer_orig'],
        answer_llm=record['answer_llm']
    )

    answer = llm(prompt, model="gpt-4o-mini")
    parsed = json.loads(answer)

    answers.append(parsed)

    print(f"Record {i+1}/{len(sample)} terminé")

Record 1/100 terminé
Record 2/100 terminé
Record 3/100 terminé
Record 4/100 terminé
Record 5/100 terminé
Record 6/100 terminé
Record 7/100 terminé
Record 8/100 terminé
Record 9/100 terminé
Record 10/100 terminé
Record 11/100 terminé
Record 12/100 terminé
Record 13/100 terminé
Record 14/100 terminé
Record 15/100 terminé
Record 16/100 terminé
Record 17/100 terminé
Record 18/100 terminé
Record 19/100 terminé
Record 20/100 terminé
Record 21/100 terminé

KeyboardInterrupt:

In [162]:
answers = []

for i, record in enumerate(sample[:10]):
    prompt = prompt_template.format(
        question=record['question'],
        answer_orig=record['answer_orig'],
        answer_llm=record['answer_llm']
    )

    answer = llm(prompt, model="gpt-4o-mini")
    parsed = json.loads(answer)

    answers.append(parsed)

    print(f"Record {i+1}/10 terminé")

Record 1/10 terminé
Record 2/10 terminé
Record 3/10 terminé
Record 4/10 terminé
Record 5/10 terminé
Record 6/10 terminé
Record 7/10 terminé
Record 8/10 terminé
Record 9/10 terminé
Record 10/10 terminé

In [163]:
df_eval = pd.DataFrame(answers)
df_eval

      relevance                                        explanation
0      relevant  The generated answer accurately provides the s...
1      relevant  The generated answer correctly addresses the i...
2      relevant  The generated answer correctly identifies the ...
3      relevant  The generated answer correctly addresses the q...
4  non relevant  The generated answer addresses a different pot...
5      relevant  The generated answer correctly identifies the ...
6      relevant  The generated answer accurately addresses the ...
7      relevant  The generated answer correctly identifies the ...
8      relevant  The generated answer correctly instructs the u...
9      relevant  The generated answer correctly identifies the ...

In [164]:
df_eval['relevance'].value_counts()

relevance
relevant        9
non relevant    1
Name: count, dtype: int64

In [165]:
(df_eval['relevance'] == 'relevant').mean()

np.float64(0.9)